// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"banking-service/internal/biz"
	"banking-service/internal/conf"
	"banking-service/internal/data"
	"banking-service/internal/server"
	"banking-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	bankingRepo := data.NewBankingRepo(dataData, logger)
	upstreamBankAPI := data.NewUpstreamBankAPIFromConfig(confData, logger)
	bankingUsecase := biz.NewBankingUsecase(bankingRepo, upstreamBankAPI, logger)
	bankingService := service.NewBankingService(bankingUsecase)
	grpcServer := server.NewGRPCServer(confServer, bankingService, logger)
	httpServer := server.NewHTTPServer(confServer, bankingService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
