// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: website/v1/website.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Site Settings Messages
type GetSiteSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteSettingsRequest) Reset() {
	*x = GetSiteSettingsRequest{}
	mi := &file_website_v1_website_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteSettingsRequest) ProtoMessage() {}

func (x *GetSiteSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSiteSettingsRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{0}
}

type GetSiteSettingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SiteSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteSettingsReply) Reset() {
	*x = GetSiteSettingsReply{}
	mi := &file_website_v1_website_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteSettingsReply) ProtoMessage() {}

func (x *GetSiteSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteSettingsReply.ProtoReflect.Descriptor instead.
func (*GetSiteSettingsReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{1}
}

func (x *GetSiteSettingsReply) GetSettings() *SiteSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateSiteSettingsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Keywords        string                 `protobuf:"bytes,3,opt,name=keywords,proto3" json:"keywords,omitempty"`
	ContactEmail    string                 `protobuf:"bytes,4,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactPhone    string                 `protobuf:"bytes,5,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	MaintenanceMode bool                   `protobuf:"varint,6,opt,name=maintenance_mode,json=maintenanceMode,proto3" json:"maintenance_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSiteSettingsRequest) Reset() {
	*x = UpdateSiteSettingsRequest{}
	mi := &file_website_v1_website_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteSettingsRequest) ProtoMessage() {}

func (x *UpdateSiteSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSiteSettingsRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSiteSettingsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSiteSettingsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSiteSettingsRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *UpdateSiteSettingsRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *UpdateSiteSettingsRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *UpdateSiteSettingsRequest) GetMaintenanceMode() bool {
	if x != nil {
		return x.MaintenanceMode
	}
	return false
}

type UpdateSiteSettingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *SiteSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteSettingsReply) Reset() {
	*x = UpdateSiteSettingsReply{}
	mi := &file_website_v1_website_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteSettingsReply) ProtoMessage() {}

func (x *UpdateSiteSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteSettingsReply.ProtoReflect.Descriptor instead.
func (*UpdateSiteSettingsReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSiteSettingsReply) GetSettings() *SiteSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SiteSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Keywords        string                 `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"`
	LogoUrl         string                 `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ContactEmail    string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactPhone    string                 `protobuf:"bytes,7,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	MaintenanceMode bool                   `protobuf:"varint,8,opt,name=maintenance_mode,json=maintenanceMode,proto3" json:"maintenance_mode,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SiteSettings) Reset() {
	*x = SiteSettings{}
	mi := &file_website_v1_website_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSettings) ProtoMessage() {}

func (x *SiteSettings) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSettings.ProtoReflect.Descriptor instead.
func (*SiteSettings) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{4}
}

func (x *SiteSettings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SiteSettings) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SiteSettings) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SiteSettings) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *SiteSettings) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *SiteSettings) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *SiteSettings) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *SiteSettings) GetMaintenanceMode() bool {
	if x != nil {
		return x.MaintenanceMode
	}
	return false
}

func (x *SiteSettings) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SiteSettings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Site Title Messages
type UpdateSiteTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteTitleRequest) Reset() {
	*x = UpdateSiteTitleRequest{}
	mi := &file_website_v1_website_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteTitleRequest) ProtoMessage() {}

func (x *UpdateSiteTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteTitleRequest.ProtoReflect.Descriptor instead.
func (*UpdateSiteTitleRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSiteTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateSiteTitleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteTitleReply) Reset() {
	*x = UpdateSiteTitleReply{}
	mi := &file_website_v1_website_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteTitleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteTitleReply) ProtoMessage() {}

func (x *UpdateSiteTitleReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteTitleReply.ProtoReflect.Descriptor instead.
func (*UpdateSiteTitleReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSiteTitleReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSiteTitleReply) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Logo Messages
type UploadLogoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogoRequest) Reset() {
	*x = UploadLogoRequest{}
	mi := &file_website_v1_website_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogoRequest) ProtoMessage() {}

func (x *UploadLogoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogoRequest.ProtoReflect.Descriptor instead.
func (*UploadLogoRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{7}
}

func (x *UploadLogoRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadLogoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadLogoRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadLogoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogoUrl       string                 `protobuf:"bytes,1,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogoReply) Reset() {
	*x = UploadLogoReply{}
	mi := &file_website_v1_website_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogoReply) ProtoMessage() {}

func (x *UploadLogoReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogoReply.ProtoReflect.Descriptor instead.
func (*UploadLogoReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{8}
}

func (x *UploadLogoReply) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *UploadLogoReply) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

type GetLogoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogoRequest) Reset() {
	*x = GetLogoRequest{}
	mi := &file_website_v1_website_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogoRequest) ProtoMessage() {}

func (x *GetLogoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogoRequest.ProtoReflect.Descriptor instead.
func (*GetLogoRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{9}
}

type GetLogoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogoUrl       string                 `protobuf:"bytes,1,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogoReply) Reset() {
	*x = GetLogoReply{}
	mi := &file_website_v1_website_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogoReply) ProtoMessage() {}

func (x *GetLogoReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogoReply.ProtoReflect.Descriptor instead.
func (*GetLogoReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{10}
}

func (x *GetLogoReply) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *GetLogoReply) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

type DeleteLogoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLogoRequest) Reset() {
	*x = DeleteLogoRequest{}
	mi := &file_website_v1_website_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogoRequest) ProtoMessage() {}

func (x *DeleteLogoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogoRequest.ProtoReflect.Descriptor instead.
func (*DeleteLogoRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{11}
}

type DeleteLogoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLogoReply) Reset() {
	*x = DeleteLogoReply{}
	mi := &file_website_v1_website_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogoReply) ProtoMessage() {}

func (x *DeleteLogoReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogoReply.ProtoReflect.Descriptor instead.
func (*DeleteLogoReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteLogoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Dynamic Settings Messages
type GetDynamicSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicSettingsRequest) Reset() {
	*x = GetDynamicSettingsRequest{}
	mi := &file_website_v1_website_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicSettingsRequest) ProtoMessage() {}

func (x *GetDynamicSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetDynamicSettingsRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{13}
}

type GetDynamicSettingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      map[string]string      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicSettingsReply) Reset() {
	*x = GetDynamicSettingsReply{}
	mi := &file_website_v1_website_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicSettingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicSettingsReply) ProtoMessage() {}

func (x *GetDynamicSettingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicSettingsReply.ProtoReflect.Descriptor instead.
func (*GetDynamicSettingsReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{14}
}

func (x *GetDynamicSettingsReply) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateDynamicSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDynamicSettingRequest) Reset() {
	*x = UpdateDynamicSettingRequest{}
	mi := &file_website_v1_website_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDynamicSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDynamicSettingRequest) ProtoMessage() {}

func (x *UpdateDynamicSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDynamicSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateDynamicSettingRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateDynamicSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateDynamicSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateDynamicSettingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *DynamicSetting        `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDynamicSettingReply) Reset() {
	*x = UpdateDynamicSettingReply{}
	mi := &file_website_v1_website_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDynamicSettingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDynamicSettingReply) ProtoMessage() {}

func (x *UpdateDynamicSettingReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDynamicSettingReply.ProtoReflect.Descriptor instead.
func (*UpdateDynamicSettingReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDynamicSettingReply) GetSetting() *DynamicSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type DeleteDynamicSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDynamicSettingRequest) Reset() {
	*x = DeleteDynamicSettingRequest{}
	mi := &file_website_v1_website_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDynamicSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDynamicSettingRequest) ProtoMessage() {}

func (x *DeleteDynamicSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDynamicSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteDynamicSettingRequest) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteDynamicSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteDynamicSettingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDynamicSettingReply) Reset() {
	*x = DeleteDynamicSettingReply{}
	mi := &file_website_v1_website_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDynamicSettingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDynamicSettingReply) ProtoMessage() {}

func (x *DeleteDynamicSettingReply) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDynamicSettingReply.ProtoReflect.Descriptor instead.
func (*DeleteDynamicSettingReply) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDynamicSettingReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DynamicSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicSetting) Reset() {
	*x = DynamicSetting{}
	mi := &file_website_v1_website_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicSetting) ProtoMessage() {}

func (x *DynamicSetting) ProtoReflect() protoreflect.Message {
	mi := &file_website_v1_website_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicSetting.ProtoReflect.Descriptor instead.
func (*DynamicSetting) Descriptor() ([]byte, []int) {
	return file_website_v1_website_proto_rawDescGZIP(), []int{19}
}

func (x *DynamicSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DynamicSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DynamicSetting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DynamicSetting) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_website_v1_website_proto protoreflect.FileDescriptor

const file_website_v1_website_proto_rawDesc = "" +
	"\n" +
	"\x18website/v1/website.proto\x12\x0eapi.website.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x18\n" +
	"\x16GetSiteSettingsRequest\"P\n" +
	"\x14GetSiteSettingsReply\x128\n" +
	"\bsettings\x18\x01 \x01(\v2\x1c.api.website.v1.SiteSettingsR\bsettings\"\xe4\x01\n" +
	"\x19UpdateSiteSettingsRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\x03 \x01(\tR\bkeywords\x12#\n" +
	"\rcontact_email\x18\x04 \x01(\tR\fcontactEmail\x12#\n" +
	"\rcontact_phone\x18\x05 \x01(\tR\fcontactPhone\x12)\n" +
	"\x10maintenance_mode\x18\x06 \x01(\bR\x0fmaintenanceMode\"S\n" +
	"\x17UpdateSiteSettingsReply\x128\n" +
	"\bsettings\x18\x01 \x01(\v2\x1c.api.website.v1.SiteSettingsR\bsettings\"\xf8\x02\n" +
	"\fSiteSettings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\x04 \x01(\tR\bkeywords\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12#\n" +
	"\rcontact_email\x18\x06 \x01(\tR\fcontactEmail\x12#\n" +
	"\rcontact_phone\x18\a \x01(\tR\fcontactPhone\x12)\n" +
	"\x10maintenance_mode\x18\b \x01(\bR\x0fmaintenanceMode\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x16UpdateSiteTitleRequest\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x05title\"g\n" +
	"\x14UpdateSiteTitleReply\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"p\n" +
	"\x11UploadLogoRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"i\n" +
	"\x0fUploadLogoReply\x12\x19\n" +
	"\blogo_url\x18\x01 \x01(\tR\alogoUrl\x12;\n" +
	"\vuploaded_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\x10\n" +
	"\x0eGetLogoRequest\"f\n" +
	"\fGetLogoReply\x12\x19\n" +
	"\blogo_url\x18\x01 \x01(\tR\alogoUrl\x12;\n" +
	"\vuploaded_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\x13\n" +
	"\x11DeleteLogoRequest\"+\n" +
	"\x0fDeleteLogoReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1b\n" +
	"\x19GetDynamicSettingsRequest\"\xa9\x01\n" +
	"\x17GetDynamicSettingsReply\x12Q\n" +
	"\bsettings\x18\x01 \x03(\v25.api.website.v1.GetDynamicSettingsReply.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x1bUpdateDynamicSettingRequest\x12\x1b\n" +
	"\x03key\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"U\n" +
	"\x19UpdateDynamicSettingReply\x128\n" +
	"\asetting\x18\x01 \x01(\v2\x1e.api.website.v1.DynamicSettingR\asetting\"8\n" +
	"\x1bDeleteDynamicSettingRequest\x12\x19\n" +
	"\x03key\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03key\"5\n" +
	"\x19DeleteDynamicSettingReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xae\x01\n" +
	"\x0eDynamicSetting\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x84\t\n" +
	"\aWebsite\x12z\n" +
	"\x0fGetSiteSettings\x12&.api.website.v1.GetSiteSettingsRequest\x1a$.api.website.v1.GetSiteSettingsReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/site/settings\x12\x86\x01\n" +
	"\x12UpdateSiteSettings\x12).api.website.v1.UpdateSiteSettingsRequest\x1a'.api.website.v1.UpdateSiteSettingsReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/site/settings\x12z\n" +
	"\x0fUpdateSiteTitle\x12&.api.website.v1.UpdateSiteTitleRequest\x1a$.api.website.v1.UpdateSiteTitleReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/site/title\x12j\n" +
	"\n" +
	"UploadLogo\x12!.api.website.v1.UploadLogoRequest\x1a\x1f.api.website.v1.UploadLogoReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/site/logo\x12^\n" +
	"\aGetLogo\x12\x1e.api.website.v1.GetLogoRequest\x1a\x1c.api.website.v1.GetLogoReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/site/logo\x12g\n" +
	"\n" +
	"DeleteLogo\x12!.api.website.v1.DeleteLogoRequest\x1a\x1f.api.website.v1.DeleteLogoReply\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/site/logo\x12\x8b\x01\n" +
	"\x12GetDynamicSettings\x12).api.website.v1.GetDynamicSettingsRequest\x1a'.api.website.v1.GetDynamicSettingsReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/site/dynamic-settings\x12\x9a\x01\n" +
	"\x14UpdateDynamicSetting\x12+.api.website.v1.UpdateDynamicSettingRequest\x1a).api.website.v1.UpdateDynamicSettingReply\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/v1/site/dynamic-settings/{key}\x12\x97\x01\n" +
	"\x14DeleteDynamicSetting\x12+.api.website.v1.DeleteDynamicSettingRequest\x1a).api.website.v1.DeleteDynamicSettingReply\"'\x82\xd3\xe4\x93\x02!*\x1f/v1/site/dynamic-settings/{key}B#Z!website-service/api/website/v1;v1b\x06proto3"

var (
	file_website_v1_website_proto_rawDescOnce sync.Once
	file_website_v1_website_proto_rawDescData []byte
)

func file_website_v1_website_proto_rawDescGZIP() []byte {
	file_website_v1_website_proto_rawDescOnce.Do(func() {
		file_website_v1_website_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_website_v1_website_proto_rawDesc), len(file_website_v1_website_proto_rawDesc)))
	})
	return file_website_v1_website_proto_rawDescData
}

var file_website_v1_website_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_website_v1_website_proto_goTypes = []any{
	(*GetSiteSettingsRequest)(nil),      // 0: api.website.v1.GetSiteSettingsRequest
	(*GetSiteSettingsReply)(nil),        // 1: api.website.v1.GetSiteSettingsReply
	(*UpdateSiteSettingsRequest)(nil),   // 2: api.website.v1.UpdateSiteSettingsRequest
	(*UpdateSiteSettingsReply)(nil),     // 3: api.website.v1.UpdateSiteSettingsReply
	(*SiteSettings)(nil),                // 4: api.website.v1.SiteSettings
	(*UpdateSiteTitleRequest)(nil),      // 5: api.website.v1.UpdateSiteTitleRequest
	(*UpdateSiteTitleReply)(nil),        // 6: api.website.v1.UpdateSiteTitleReply
	(*UploadLogoRequest)(nil),           // 7: api.website.v1.UploadLogoRequest
	(*UploadLogoReply)(nil),             // 8: api.website.v1.UploadLogoReply
	(*GetLogoRequest)(nil),              // 9: api.website.v1.GetLogoRequest
	(*GetLogoReply)(nil),                // 10: api.website.v1.GetLogoReply
	(*DeleteLogoRequest)(nil),           // 11: api.website.v1.DeleteLogoRequest
	(*DeleteLogoReply)(nil),             // 12: api.website.v1.DeleteLogoReply
	(*GetDynamicSettingsRequest)(nil),   // 13: api.website.v1.GetDynamicSettingsRequest
	(*GetDynamicSettingsReply)(nil),     // 14: api.website.v1.GetDynamicSettingsReply
	(*UpdateDynamicSettingRequest)(nil), // 15: api.website.v1.UpdateDynamicSettingRequest
	(*UpdateDynamicSettingReply)(nil),   // 16: api.website.v1.UpdateDynamicSettingReply
	(*DeleteDynamicSettingRequest)(nil), // 17: api.website.v1.DeleteDynamicSettingRequest
	(*DeleteDynamicSettingReply)(nil),   // 18: api.website.v1.DeleteDynamicSettingReply
	(*DynamicSetting)(nil),              // 19: api.website.v1.DynamicSetting
	nil,                                 // 20: api.website.v1.GetDynamicSettingsReply.SettingsEntry
	(*timestamppb.Timestamp)(nil),       // 21: google.protobuf.Timestamp
}
var file_website_v1_website_proto_depIdxs = []int32{
	4,  // 0: api.website.v1.GetSiteSettingsReply.settings:type_name -> api.website.v1.SiteSettings
	4,  // 1: api.website.v1.UpdateSiteSettingsReply.settings:type_name -> api.website.v1.SiteSettings
	21, // 2: api.website.v1.SiteSettings.created_at:type_name -> google.protobuf.Timestamp
	21, // 3: api.website.v1.SiteSettings.updated_at:type_name -> google.protobuf.Timestamp
	21, // 4: api.website.v1.UpdateSiteTitleReply.updated_at:type_name -> google.protobuf.Timestamp
	21, // 5: api.website.v1.UploadLogoReply.uploaded_at:type_name -> google.protobuf.Timestamp
	21, // 6: api.website.v1.GetLogoReply.uploaded_at:type_name -> google.protobuf.Timestamp
	20, // 7: api.website.v1.GetDynamicSettingsReply.settings:type_name -> api.website.v1.GetDynamicSettingsReply.SettingsEntry
	19, // 8: api.website.v1.UpdateDynamicSettingReply.setting:type_name -> api.website.v1.DynamicSetting
	21, // 9: api.website.v1.DynamicSetting.created_at:type_name -> google.protobuf.Timestamp
	21, // 10: api.website.v1.DynamicSetting.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: api.website.v1.Website.GetSiteSettings:input_type -> api.website.v1.GetSiteSettingsRequest
	2,  // 12: api.website.v1.Website.UpdateSiteSettings:input_type -> api.website.v1.UpdateSiteSettingsRequest
	5,  // 13: api.website.v1.Website.UpdateSiteTitle:input_type -> api.website.v1.UpdateSiteTitleRequest
	7,  // 14: api.website.v1.Website.UploadLogo:input_type -> api.website.v1.UploadLogoRequest
	9,  // 15: api.website.v1.Website.GetLogo:input_type -> api.website.v1.GetLogoRequest
	11, // 16: api.website.v1.Website.DeleteLogo:input_type -> api.website.v1.DeleteLogoRequest
	13, // 17: api.website.v1.Website.GetDynamicSettings:input_type -> api.website.v1.GetDynamicSettingsRequest
	15, // 18: api.website.v1.Website.UpdateDynamicSetting:input_type -> api.website.v1.UpdateDynamicSettingRequest
	17, // 19: api.website.v1.Website.DeleteDynamicSetting:input_type -> api.website.v1.DeleteDynamicSettingRequest
	1,  // 20: api.website.v1.Website.GetSiteSettings:output_type -> api.website.v1.GetSiteSettingsReply
	3,  // 21: api.website.v1.Website.UpdateSiteSettings:output_type -> api.website.v1.UpdateSiteSettingsReply
	6,  // 22: api.website.v1.Website.UpdateSiteTitle:output_type -> api.website.v1.UpdateSiteTitleReply
	8,  // 23: api.website.v1.Website.UploadLogo:output_type -> api.website.v1.UploadLogoReply
	10, // 24: api.website.v1.Website.GetLogo:output_type -> api.website.v1.GetLogoReply
	12, // 25: api.website.v1.Website.DeleteLogo:output_type -> api.website.v1.DeleteLogoReply
	14, // 26: api.website.v1.Website.GetDynamicSettings:output_type -> api.website.v1.GetDynamicSettingsReply
	16, // 27: api.website.v1.Website.UpdateDynamicSetting:output_type -> api.website.v1.UpdateDynamicSettingReply
	18, // 28: api.website.v1.Website.DeleteDynamicSetting:output_type -> api.website.v1.DeleteDynamicSettingReply
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_website_v1_website_proto_init() }
func file_website_v1_website_proto_init() {
	if File_website_v1_website_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_website_v1_website_proto_rawDesc), len(file_website_v1_website_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_website_v1_website_proto_goTypes,
		DependencyIndexes: file_website_v1_website_proto_depIdxs,
		MessageInfos:      file_website_v1_website_proto_msgTypes,
	}.Build()
	File_website_v1_website_proto = out.File
	file_website_v1_website_proto_goTypes = nil
	file_website_v1_website_proto_depIdxs = nil
}
