// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: website/v1/website.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Website_GetSiteSettings_FullMethodName      = "/api.website.v1.Website/GetSiteSettings"
	Website_UpdateSiteSettings_FullMethodName   = "/api.website.v1.Website/UpdateSiteSettings"
	Website_UpdateSiteTitle_FullMethodName      = "/api.website.v1.Website/UpdateSiteTitle"
	Website_UploadLogo_FullMethodName           = "/api.website.v1.Website/UploadLogo"
	Website_GetLogo_FullMethodName              = "/api.website.v1.Website/GetLogo"
	Website_DeleteLogo_FullMethodName           = "/api.website.v1.Website/DeleteLogo"
	Website_GetDynamicSettings_FullMethodName   = "/api.website.v1.Website/GetDynamicSettings"
	Website_UpdateDynamicSetting_FullMethodName = "/api.website.v1.Website/UpdateDynamicSetting"
	Website_DeleteDynamicSetting_FullMethodName = "/api.website.v1.Website/DeleteDynamicSetting"
)

// WebsiteClient is the client API for Website service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Website service handles website management features
type WebsiteClient interface {
	// Site Settings
	GetSiteSettings(ctx context.Context, in *GetSiteSettingsRequest, opts ...grpc.CallOption) (*GetSiteSettingsReply, error)
	UpdateSiteSettings(ctx context.Context, in *UpdateSiteSettingsRequest, opts ...grpc.CallOption) (*UpdateSiteSettingsReply, error)
	// Site Title
	UpdateSiteTitle(ctx context.Context, in *UpdateSiteTitleRequest, opts ...grpc.CallOption) (*UpdateSiteTitleReply, error)
	// Logo Management
	UploadLogo(ctx context.Context, in *UploadLogoRequest, opts ...grpc.CallOption) (*UploadLogoReply, error)
	GetLogo(ctx context.Context, in *GetLogoRequest, opts ...grpc.CallOption) (*GetLogoReply, error)
	DeleteLogo(ctx context.Context, in *DeleteLogoRequest, opts ...grpc.CallOption) (*DeleteLogoReply, error)
	// Dynamic Settings
	GetDynamicSettings(ctx context.Context, in *GetDynamicSettingsRequest, opts ...grpc.CallOption) (*GetDynamicSettingsReply, error)
	UpdateDynamicSetting(ctx context.Context, in *UpdateDynamicSettingRequest, opts ...grpc.CallOption) (*UpdateDynamicSettingReply, error)
	DeleteDynamicSetting(ctx context.Context, in *DeleteDynamicSettingRequest, opts ...grpc.CallOption) (*DeleteDynamicSettingReply, error)
}

type websiteClient struct {
	cc grpc.ClientConnInterface
}

func NewWebsiteClient(cc grpc.ClientConnInterface) WebsiteClient {
	return &websiteClient{cc}
}

func (c *websiteClient) GetSiteSettings(ctx context.Context, in *GetSiteSettingsRequest, opts ...grpc.CallOption) (*GetSiteSettingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSiteSettingsReply)
	err := c.cc.Invoke(ctx, Website_GetSiteSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteClient) UpdateSiteSettings(ctx context.Context, in *UpdateSiteSettingsRequest, opts ...grpc.CallOption) (*UpdateSiteSettingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSiteSettingsReply)
	err := c.cc.Invoke(ctx, Website_UpdateSiteSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteClient) UpdateSiteTitle(ctx context.Context, in *UpdateSiteTitleRequest, opts ...grpc.CallOption) (*UpdateSiteTitleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSiteTitleReply)
	err := c.cc.Invoke(ctx, Website_UpdateSiteTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteClient) UploadLogo(ctx context.Context, in *UploadLogoRequest, opts ...grpc.CallOption) (*UploadLogoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadLogoReply)
	err := c.cc.Invoke(ctx, Website_UploadLogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteClient) GetLogo(ctx context.Context, in *GetLogoRequest, opts ...grpc.CallOption) (*GetLogoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogoReply)
	err := c.cc.Invoke(ctx, Website_GetLogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteClient) DeleteLogo(ctx context.Context, in *DeleteLogoRequest, opts ...grpc.CallOption) (*DeleteLogoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLogoReply)
	err := c.cc.Invoke(ctx, Website_DeleteLogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteClient) GetDynamicSettings(ctx context.Context, in *GetDynamicSettingsRequest, opts ...grpc.CallOption) (*GetDynamicSettingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDynamicSettingsReply)
	err := c.cc.Invoke(ctx, Website_GetDynamicSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteClient) UpdateDynamicSetting(ctx context.Context, in *UpdateDynamicSettingRequest, opts ...grpc.CallOption) (*UpdateDynamicSettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDynamicSettingReply)
	err := c.cc.Invoke(ctx, Website_UpdateDynamicSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *websiteClient) DeleteDynamicSetting(ctx context.Context, in *DeleteDynamicSettingRequest, opts ...grpc.CallOption) (*DeleteDynamicSettingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDynamicSettingReply)
	err := c.cc.Invoke(ctx, Website_DeleteDynamicSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebsiteServer is the server API for Website service.
// All implementations must embed UnimplementedWebsiteServer
// for forward compatibility.
//
// Website service handles website management features
type WebsiteServer interface {
	// Site Settings
	GetSiteSettings(context.Context, *GetSiteSettingsRequest) (*GetSiteSettingsReply, error)
	UpdateSiteSettings(context.Context, *UpdateSiteSettingsRequest) (*UpdateSiteSettingsReply, error)
	// Site Title
	UpdateSiteTitle(context.Context, *UpdateSiteTitleRequest) (*UpdateSiteTitleReply, error)
	// Logo Management
	UploadLogo(context.Context, *UploadLogoRequest) (*UploadLogoReply, error)
	GetLogo(context.Context, *GetLogoRequest) (*GetLogoReply, error)
	DeleteLogo(context.Context, *DeleteLogoRequest) (*DeleteLogoReply, error)
	// Dynamic Settings
	GetDynamicSettings(context.Context, *GetDynamicSettingsRequest) (*GetDynamicSettingsReply, error)
	UpdateDynamicSetting(context.Context, *UpdateDynamicSettingRequest) (*UpdateDynamicSettingReply, error)
	DeleteDynamicSetting(context.Context, *DeleteDynamicSettingRequest) (*DeleteDynamicSettingReply, error)
	mustEmbedUnimplementedWebsiteServer()
}

// UnimplementedWebsiteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebsiteServer struct{}

func (UnimplementedWebsiteServer) GetSiteSettings(context.Context, *GetSiteSettingsRequest) (*GetSiteSettingsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSiteSettings not implemented")
}
func (UnimplementedWebsiteServer) UpdateSiteSettings(context.Context, *UpdateSiteSettingsRequest) (*UpdateSiteSettingsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSiteSettings not implemented")
}
func (UnimplementedWebsiteServer) UpdateSiteTitle(context.Context, *UpdateSiteTitleRequest) (*UpdateSiteTitleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSiteTitle not implemented")
}
func (UnimplementedWebsiteServer) UploadLogo(context.Context, *UploadLogoRequest) (*UploadLogoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLogo not implemented")
}
func (UnimplementedWebsiteServer) GetLogo(context.Context, *GetLogoRequest) (*GetLogoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogo not implemented")
}
func (UnimplementedWebsiteServer) DeleteLogo(context.Context, *DeleteLogoRequest) (*DeleteLogoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLogo not implemented")
}
func (UnimplementedWebsiteServer) GetDynamicSettings(context.Context, *GetDynamicSettingsRequest) (*GetDynamicSettingsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDynamicSettings not implemented")
}
func (UnimplementedWebsiteServer) UpdateDynamicSetting(context.Context, *UpdateDynamicSettingRequest) (*UpdateDynamicSettingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDynamicSetting not implemented")
}
func (UnimplementedWebsiteServer) DeleteDynamicSetting(context.Context, *DeleteDynamicSettingRequest) (*DeleteDynamicSettingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDynamicSetting not implemented")
}
func (UnimplementedWebsiteServer) mustEmbedUnimplementedWebsiteServer() {}
func (UnimplementedWebsiteServer) testEmbeddedByValue()                 {}

// UnsafeWebsiteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebsiteServer will
// result in compilation errors.
type UnsafeWebsiteServer interface {
	mustEmbedUnimplementedWebsiteServer()
}

func RegisterWebsiteServer(s grpc.ServiceRegistrar, srv WebsiteServer) {
	// If the following call pancis, it indicates UnimplementedWebsiteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Website_ServiceDesc, srv)
}

func _Website_GetSiteSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).GetSiteSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_GetSiteSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).GetSiteSettings(ctx, req.(*GetSiteSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Website_UpdateSiteSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSiteSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).UpdateSiteSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_UpdateSiteSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).UpdateSiteSettings(ctx, req.(*UpdateSiteSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Website_UpdateSiteTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSiteTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).UpdateSiteTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_UpdateSiteTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).UpdateSiteTitle(ctx, req.(*UpdateSiteTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Website_UploadLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadLogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).UploadLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_UploadLogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).UploadLogo(ctx, req.(*UploadLogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Website_GetLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).GetLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_GetLogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).GetLogo(ctx, req.(*GetLogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Website_DeleteLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).DeleteLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_DeleteLogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).DeleteLogo(ctx, req.(*DeleteLogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Website_GetDynamicSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDynamicSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).GetDynamicSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_GetDynamicSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).GetDynamicSettings(ctx, req.(*GetDynamicSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Website_UpdateDynamicSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDynamicSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).UpdateDynamicSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_UpdateDynamicSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).UpdateDynamicSetting(ctx, req.(*UpdateDynamicSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Website_DeleteDynamicSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDynamicSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsiteServer).DeleteDynamicSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Website_DeleteDynamicSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsiteServer).DeleteDynamicSetting(ctx, req.(*DeleteDynamicSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Website_ServiceDesc is the grpc.ServiceDesc for Website service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Website_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.website.v1.Website",
	HandlerType: (*WebsiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSiteSettings",
			Handler:    _Website_GetSiteSettings_Handler,
		},
		{
			MethodName: "UpdateSiteSettings",
			Handler:    _Website_UpdateSiteSettings_Handler,
		},
		{
			MethodName: "UpdateSiteTitle",
			Handler:    _Website_UpdateSiteTitle_Handler,
		},
		{
			MethodName: "UploadLogo",
			Handler:    _Website_UploadLogo_Handler,
		},
		{
			MethodName: "GetLogo",
			Handler:    _Website_GetLogo_Handler,
		},
		{
			MethodName: "DeleteLogo",
			Handler:    _Website_DeleteLogo_Handler,
		},
		{
			MethodName: "GetDynamicSettings",
			Handler:    _Website_GetDynamicSettings_Handler,
		},
		{
			MethodName: "UpdateDynamicSetting",
			Handler:    _Website_UpdateDynamicSetting_Handler,
		},
		{
			MethodName: "DeleteDynamicSetting",
			Handler:    _Website_DeleteDynamicSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "website/v1/website.proto",
}
