// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.12
// source: website/v1/website.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWebsiteDeleteDynamicSetting = "/api.website.v1.Website/DeleteDynamicSetting"
const OperationWebsiteDeleteLogo = "/api.website.v1.Website/DeleteLogo"
const OperationWebsiteGetDynamicSettings = "/api.website.v1.Website/GetDynamicSettings"
const OperationWebsiteGetLogo = "/api.website.v1.Website/GetLogo"
const OperationWebsiteGetSiteSettings = "/api.website.v1.Website/GetSiteSettings"
const OperationWebsiteUpdateDynamicSetting = "/api.website.v1.Website/UpdateDynamicSetting"
const OperationWebsiteUpdateSiteSettings = "/api.website.v1.Website/UpdateSiteSettings"
const OperationWebsiteUpdateSiteTitle = "/api.website.v1.Website/UpdateSiteTitle"
const OperationWebsiteUploadLogo = "/api.website.v1.Website/UploadLogo"

type WebsiteHTTPServer interface {
	DeleteDynamicSetting(context.Context, *DeleteDynamicSettingRequest) (*DeleteDynamicSettingReply, error)
	DeleteLogo(context.Context, *DeleteLogoRequest) (*DeleteLogoReply, error)
	// GetDynamicSettings Dynamic Settings
	GetDynamicSettings(context.Context, *GetDynamicSettingsRequest) (*GetDynamicSettingsReply, error)
	GetLogo(context.Context, *GetLogoRequest) (*GetLogoReply, error)
	// GetSiteSettings Site Settings
	GetSiteSettings(context.Context, *GetSiteSettingsRequest) (*GetSiteSettingsReply, error)
	UpdateDynamicSetting(context.Context, *UpdateDynamicSettingRequest) (*UpdateDynamicSettingReply, error)
	UpdateSiteSettings(context.Context, *UpdateSiteSettingsRequest) (*UpdateSiteSettingsReply, error)
	// UpdateSiteTitle Site Title
	UpdateSiteTitle(context.Context, *UpdateSiteTitleRequest) (*UpdateSiteTitleReply, error)
	// UploadLogo Logo Management
	UploadLogo(context.Context, *UploadLogoRequest) (*UploadLogoReply, error)
}

func RegisterWebsiteHTTPServer(s *http.Server, srv WebsiteHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/site/settings", _Website_GetSiteSettings0_HTTP_Handler(srv))
	r.PUT("/v1/site/settings", _Website_UpdateSiteSettings0_HTTP_Handler(srv))
	r.PUT("/v1/site/title", _Website_UpdateSiteTitle0_HTTP_Handler(srv))
	r.POST("/v1/site/logo", _Website_UploadLogo0_HTTP_Handler(srv))
	r.GET("/v1/site/logo", _Website_GetLogo0_HTTP_Handler(srv))
	r.DELETE("/v1/site/logo", _Website_DeleteLogo0_HTTP_Handler(srv))
	r.GET("/v1/site/dynamic-settings", _Website_GetDynamicSettings0_HTTP_Handler(srv))
	r.PUT("/v1/site/dynamic-settings/{key}", _Website_UpdateDynamicSetting0_HTTP_Handler(srv))
	r.DELETE("/v1/site/dynamic-settings/{key}", _Website_DeleteDynamicSetting0_HTTP_Handler(srv))
}

func _Website_GetSiteSettings0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSiteSettingsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteGetSiteSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSiteSettings(ctx, req.(*GetSiteSettingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSiteSettingsReply)
		return ctx.Result(200, reply)
	}
}

func _Website_UpdateSiteSettings0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSiteSettingsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteUpdateSiteSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSiteSettings(ctx, req.(*UpdateSiteSettingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSiteSettingsReply)
		return ctx.Result(200, reply)
	}
}

func _Website_UpdateSiteTitle0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSiteTitleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteUpdateSiteTitle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSiteTitle(ctx, req.(*UpdateSiteTitleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSiteTitleReply)
		return ctx.Result(200, reply)
	}
}

func _Website_UploadLogo0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadLogoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteUploadLogo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadLogo(ctx, req.(*UploadLogoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadLogoReply)
		return ctx.Result(200, reply)
	}
}

func _Website_GetLogo0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLogoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteGetLogo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLogo(ctx, req.(*GetLogoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLogoReply)
		return ctx.Result(200, reply)
	}
}

func _Website_DeleteLogo0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteLogoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteDeleteLogo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteLogo(ctx, req.(*DeleteLogoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteLogoReply)
		return ctx.Result(200, reply)
	}
}

func _Website_GetDynamicSettings0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDynamicSettingsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteGetDynamicSettings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDynamicSettings(ctx, req.(*GetDynamicSettingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDynamicSettingsReply)
		return ctx.Result(200, reply)
	}
}

func _Website_UpdateDynamicSetting0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDynamicSettingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteUpdateDynamicSetting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDynamicSetting(ctx, req.(*UpdateDynamicSettingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateDynamicSettingReply)
		return ctx.Result(200, reply)
	}
}

func _Website_DeleteDynamicSetting0_HTTP_Handler(srv WebsiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDynamicSettingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWebsiteDeleteDynamicSetting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDynamicSetting(ctx, req.(*DeleteDynamicSettingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDynamicSettingReply)
		return ctx.Result(200, reply)
	}
}

type WebsiteHTTPClient interface {
	DeleteDynamicSetting(ctx context.Context, req *DeleteDynamicSettingRequest, opts ...http.CallOption) (rsp *DeleteDynamicSettingReply, err error)
	DeleteLogo(ctx context.Context, req *DeleteLogoRequest, opts ...http.CallOption) (rsp *DeleteLogoReply, err error)
	// GetDynamicSettings Dynamic Settings
	GetDynamicSettings(ctx context.Context, req *GetDynamicSettingsRequest, opts ...http.CallOption) (rsp *GetDynamicSettingsReply, err error)
	GetLogo(ctx context.Context, req *GetLogoRequest, opts ...http.CallOption) (rsp *GetLogoReply, err error)
	// GetSiteSettings Site Settings
	GetSiteSettings(ctx context.Context, req *GetSiteSettingsRequest, opts ...http.CallOption) (rsp *GetSiteSettingsReply, err error)
	UpdateDynamicSetting(ctx context.Context, req *UpdateDynamicSettingRequest, opts ...http.CallOption) (rsp *UpdateDynamicSettingReply, err error)
	UpdateSiteSettings(ctx context.Context, req *UpdateSiteSettingsRequest, opts ...http.CallOption) (rsp *UpdateSiteSettingsReply, err error)
	// UpdateSiteTitle Site Title
	UpdateSiteTitle(ctx context.Context, req *UpdateSiteTitleRequest, opts ...http.CallOption) (rsp *UpdateSiteTitleReply, err error)
	// UploadLogo Logo Management
	UploadLogo(ctx context.Context, req *UploadLogoRequest, opts ...http.CallOption) (rsp *UploadLogoReply, err error)
}

type WebsiteHTTPClientImpl struct {
	cc *http.Client
}

func NewWebsiteHTTPClient(client *http.Client) WebsiteHTTPClient {
	return &WebsiteHTTPClientImpl{client}
}

func (c *WebsiteHTTPClientImpl) DeleteDynamicSetting(ctx context.Context, in *DeleteDynamicSettingRequest, opts ...http.CallOption) (*DeleteDynamicSettingReply, error) {
	var out DeleteDynamicSettingReply
	pattern := "/v1/site/dynamic-settings/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWebsiteDeleteDynamicSetting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WebsiteHTTPClientImpl) DeleteLogo(ctx context.Context, in *DeleteLogoRequest, opts ...http.CallOption) (*DeleteLogoReply, error) {
	var out DeleteLogoReply
	pattern := "/v1/site/logo"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWebsiteDeleteLogo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDynamicSettings Dynamic Settings
func (c *WebsiteHTTPClientImpl) GetDynamicSettings(ctx context.Context, in *GetDynamicSettingsRequest, opts ...http.CallOption) (*GetDynamicSettingsReply, error) {
	var out GetDynamicSettingsReply
	pattern := "/v1/site/dynamic-settings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWebsiteGetDynamicSettings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WebsiteHTTPClientImpl) GetLogo(ctx context.Context, in *GetLogoRequest, opts ...http.CallOption) (*GetLogoReply, error) {
	var out GetLogoReply
	pattern := "/v1/site/logo"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWebsiteGetLogo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSiteSettings Site Settings
func (c *WebsiteHTTPClientImpl) GetSiteSettings(ctx context.Context, in *GetSiteSettingsRequest, opts ...http.CallOption) (*GetSiteSettingsReply, error) {
	var out GetSiteSettingsReply
	pattern := "/v1/site/settings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWebsiteGetSiteSettings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WebsiteHTTPClientImpl) UpdateDynamicSetting(ctx context.Context, in *UpdateDynamicSettingRequest, opts ...http.CallOption) (*UpdateDynamicSettingReply, error) {
	var out UpdateDynamicSettingReply
	pattern := "/v1/site/dynamic-settings/{key}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWebsiteUpdateDynamicSetting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WebsiteHTTPClientImpl) UpdateSiteSettings(ctx context.Context, in *UpdateSiteSettingsRequest, opts ...http.CallOption) (*UpdateSiteSettingsReply, error) {
	var out UpdateSiteSettingsReply
	pattern := "/v1/site/settings"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWebsiteUpdateSiteSettings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSiteTitle Site Title
func (c *WebsiteHTTPClientImpl) UpdateSiteTitle(ctx context.Context, in *UpdateSiteTitleRequest, opts ...http.CallOption) (*UpdateSiteTitleReply, error) {
	var out UpdateSiteTitleReply
	pattern := "/v1/site/title"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWebsiteUpdateSiteTitle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadLogo Logo Management
func (c *WebsiteHTTPClientImpl) UploadLogo(ctx context.Context, in *UploadLogoRequest, opts ...http.CallOption) (*UploadLogoReply, error) {
	var out UploadLogoReply
	pattern := "/v1/site/logo"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWebsiteUploadLogo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
