// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: membership/v1/membership.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Authentication Messages
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,4,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RegisterReply) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginReply) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReply) Reset() {
	*x = RefreshTokenReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReply) ProtoMessage() {}

func (x *RefreshTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReply.ProtoReflect.Descriptor instead.
func (*RefreshTokenReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenReply) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// User Profile Messages
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{6}
}

type GetProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReply) Reset() {
	*x = GetProfileReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReply) ProtoMessage() {}

func (x *GetProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReply.ProtoReflect.Descriptor instead.
func (*GetProfileReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateProfileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReply) Reset() {
	*x = UpdateProfileReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReply) ProtoMessage() {}

func (x *UpdateProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReply.ProtoReflect.Descriptor instead.
func (*UpdateProfileReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,6,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_membership_v1_membership_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{10}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Asset Management Messages
type GetAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsRequest) Reset() {
	*x = GetAssetsRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsRequest) ProtoMessage() {}

func (x *GetAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{11}
}

type GetAssetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	TotalBalance  float64                `protobuf:"fixed64,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsReply) Reset() {
	*x = GetAssetsReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsReply) ProtoMessage() {}

func (x *GetAssetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsReply.ProtoReflect.Descriptor instead.
func (*GetAssetsReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{12}
}

func (x *GetAssetsReply) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *GetAssetsReply) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

type UpdateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // "add" or "subtract"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *UpdateAssetRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateAssetRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type UpdateAssetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetReply) Reset() {
	*x = UpdateAssetReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetReply) ProtoMessage() {}

func (x *UpdateAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetReply.ProtoReflect.Descriptor instead.
func (*UpdateAssetReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAssetReply) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetType     string                 `protobuf:"bytes,3,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"` // e.g., "USD", "EUR", "BTC"
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_membership_v1_membership_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{15}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Asset) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *Asset) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Referral System Messages
type GetReferralsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralsRequest) Reset() {
	*x = GetReferralsRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralsRequest) ProtoMessage() {}

func (x *GetReferralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralsRequest.ProtoReflect.Descriptor instead.
func (*GetReferralsRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{16}
}

func (x *GetReferralsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetReferralsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetReferralsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referrals     []*Referral            `protobuf:"bytes,1,rep,name=referrals,proto3" json:"referrals,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TotalEarnings float64                `protobuf:"fixed64,3,opt,name=total_earnings,json=totalEarnings,proto3" json:"total_earnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferralsReply) Reset() {
	*x = GetReferralsReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferralsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferralsReply) ProtoMessage() {}

func (x *GetReferralsReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferralsReply.ProtoReflect.Descriptor instead.
func (*GetReferralsReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{17}
}

func (x *GetReferralsReply) GetReferrals() []*Referral {
	if x != nil {
		return x.Referrals
	}
	return nil
}

func (x *GetReferralsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetReferralsReply) GetTotalEarnings() float64 {
	if x != nil {
		return x.TotalEarnings
	}
	return 0
}

type Referral struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReferredUserId   string                 `protobuf:"bytes,2,opt,name=referred_user_id,json=referredUserId,proto3" json:"referred_user_id,omitempty"`
	ReferredUsername string                 `protobuf:"bytes,3,opt,name=referred_username,json=referredUsername,proto3" json:"referred_username,omitempty"`
	Earnings         float64                `protobuf:"fixed64,4,opt,name=earnings,proto3" json:"earnings,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "pending", "approved", "paid"
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Referral) Reset() {
	*x = Referral{}
	mi := &file_membership_v1_membership_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Referral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Referral) ProtoMessage() {}

func (x *Referral) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Referral.ProtoReflect.Descriptor instead.
func (*Referral) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{18}
}

func (x *Referral) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Referral) GetReferredUserId() string {
	if x != nil {
		return x.ReferredUserId
	}
	return ""
}

func (x *Referral) GetReferredUsername() string {
	if x != nil {
		return x.ReferredUsername
	}
	return ""
}

func (x *Referral) GetEarnings() float64 {
	if x != nil {
		return x.Earnings
	}
	return 0
}

func (x *Referral) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Referral) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type WithdrawalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Amount         float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod  string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentDetails string                 `protobuf:"bytes,3,opt,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WithdrawalRequest) Reset() {
	*x = WithdrawalRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalRequest) ProtoMessage() {}

func (x *WithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalRequest.ProtoReflect.Descriptor instead.
func (*WithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{19}
}

func (x *WithdrawalRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawalRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *WithdrawalRequest) GetPaymentDetails() string {
	if x != nil {
		return x.PaymentDetails
	}
	return ""
}

type WithdrawalReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawal    *Withdrawal            `protobuf:"bytes,1,opt,name=withdrawal,proto3" json:"withdrawal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawalReply) Reset() {
	*x = WithdrawalReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalReply) ProtoMessage() {}

func (x *WithdrawalReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalReply.ProtoReflect.Descriptor instead.
func (*WithdrawalReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{20}
}

func (x *WithdrawalReply) GetWithdrawal() *Withdrawal {
	if x != nil {
		return x.Withdrawal
	}
	return nil
}

type GetWithdrawalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawalsRequest) Reset() {
	*x = GetWithdrawalsRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawalsRequest) ProtoMessage() {}

func (x *GetWithdrawalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawalsRequest.ProtoReflect.Descriptor instead.
func (*GetWithdrawalsRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{21}
}

func (x *GetWithdrawalsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetWithdrawalsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetWithdrawalsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawals   []*Withdrawal          `protobuf:"bytes,1,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawalsReply) Reset() {
	*x = GetWithdrawalsReply{}
	mi := &file_membership_v1_membership_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawalsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawalsReply) ProtoMessage() {}

func (x *GetWithdrawalsReply) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawalsReply.ProtoReflect.Descriptor instead.
func (*GetWithdrawalsReply) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{22}
}

func (x *GetWithdrawalsReply) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *GetWithdrawalsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Withdrawal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "pending", "processing", "completed", "rejected"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Withdrawal) Reset() {
	*x = Withdrawal{}
	mi := &file_membership_v1_membership_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdrawal) ProtoMessage() {}

func (x *Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdrawal.ProtoReflect.Descriptor instead.
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{23}
}

func (x *Withdrawal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Withdrawal) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Withdrawal) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Withdrawal) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Withdrawal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Withdrawal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Withdrawal) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_membership_v1_membership_proto protoreflect.FileDescriptor

const file_membership_v1_membership_proto_rawDesc = "" +
	"\n" +
	"\x1emembership/v1/membership.proto\x12\x11api.membership.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xa3\x01\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\x05email\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x05`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\bR\bpassword\x12%\n" +
	"\busername\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x182R\busername\x12#\n" +
	"\rreferral_code\x18\x04 \x01(\tR\freferralCode\"\xab\x01\n" +
	"\rRegisterReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"R\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\"\xa8\x01\n" +
	"\n" +
	"LoginReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"C\n" +
	"\x13RefreshTokenRequest\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\frefreshToken\"\x96\x01\n" +
	"\x11RefreshTokenReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x13\n" +
	"\x11GetProfileRequest\">\n" +
	"\x0fGetProfileReply\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.api.membership.v1.UserR\x04user\"g\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"A\n" +
	"\x12UpdateProfileReply\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.api.membership.v1.UserR\x04user\"\x98\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12#\n" +
	"\rreferral_code\x18\x06 \x01(\tR\freferralCode\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x12\n" +
	"\x10GetAssetsRequest\"g\n" +
	"\x0eGetAssetsReply\x120\n" +
	"\x06assets\x18\x01 \x03(\v2\x18.api.membership.v1.AssetR\x06assets\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x01R\ftotalBalance\"e\n" +
	"\x12UpdateAssetRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\"B\n" +
	"\x10UpdateAssetReply\x12.\n" +
	"\x05asset\x18\x01 \x01(\v2\x18.api.membership.v1.AssetR\x05asset\"\xdf\x01\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x03 \x01(\tR\tassetType\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"F\n" +
	"\x13GetReferralsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8b\x01\n" +
	"\x11GetReferralsReply\x129\n" +
	"\treferrals\x18\x01 \x03(\v2\x1b.api.membership.v1.ReferralR\treferrals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12%\n" +
	"\x0etotal_earnings\x18\x03 \x01(\x01R\rtotalEarnings\"\xe0\x01\n" +
	"\bReferral\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10referred_user_id\x18\x02 \x01(\tR\x0ereferredUserId\x12+\n" +
	"\x11referred_username\x18\x03 \x01(\tR\x10referredUsername\x12\x1a\n" +
	"\bearnings\x18\x04 \x01(\x01R\bearnings\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8b\x01\n" +
	"\x11WithdrawalRequest\x12&\n" +
	"\x06amount\x18\x01 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12'\n" +
	"\x0fpayment_details\x18\x03 \x01(\tR\x0epaymentDetails\"P\n" +
	"\x0fWithdrawalReply\x12=\n" +
	"\n" +
	"withdrawal\x18\x01 \x01(\v2\x1d.api.membership.v1.WithdrawalR\n" +
	"withdrawal\"H\n" +
	"\x15GetWithdrawalsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"l\n" +
	"\x13GetWithdrawalsReply\x12?\n" +
	"\vwithdrawals\x18\x01 \x03(\v2\x1d.api.membership.v1.WithdrawalR\vwithdrawals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x82\x02\n" +
	"\n" +
	"Withdrawal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xc0\t\n" +
	"\n" +
	"Membership\x12n\n" +
	"\bRegister\x12\".api.membership.v1.RegisterRequest\x1a .api.membership.v1.RegisterReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12b\n" +
	"\x05Login\x12\x1f.api.membership.v1.LoginRequest\x1a\x1d.api.membership.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12y\n" +
	"\fRefreshToken\x12&.api.membership.v1.RefreshTokenRequest\x1a$.api.membership.v1.RefreshTokenReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12q\n" +
	"\n" +
	"GetProfile\x12$.api.membership.v1.GetProfileRequest\x1a\".api.membership.v1.GetProfileReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/users/profile\x12}\n" +
	"\rUpdateProfile\x12'.api.membership.v1.UpdateProfileRequest\x1a%.api.membership.v1.UpdateProfileReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/users/profile\x12m\n" +
	"\tGetAssets\x12#.api.membership.v1.GetAssetsRequest\x1a!.api.membership.v1.GetAssetsReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/users/assets\x12\x81\x01\n" +
	"\vUpdateAsset\x12%.api.membership.v1.UpdateAssetRequest\x1a#.api.membership.v1.UpdateAssetReply\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/v1/users/assets/{asset_id}\x12y\n" +
	"\fGetReferrals\x12&.api.membership.v1.GetReferralsRequest\x1a$.api.membership.v1.GetReferralsReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/referrals\x12\x7f\n" +
	"\x11RequestWithdrawal\x12$.api.membership.v1.WithdrawalRequest\x1a\".api.membership.v1.WithdrawalReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/users/withdrawals\x12\x81\x01\n" +
	"\x0eGetWithdrawals\x12(.api.membership.v1.GetWithdrawalsRequest\x1a&.api.membership.v1.GetWithdrawalsReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/users/withdrawalsB)Z'membership-service/api/membership/v1;v1b\x06proto3"

var (
	file_membership_v1_membership_proto_rawDescOnce sync.Once
	file_membership_v1_membership_proto_rawDescData []byte
)

func file_membership_v1_membership_proto_rawDescGZIP() []byte {
	file_membership_v1_membership_proto_rawDescOnce.Do(func() {
		file_membership_v1_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_membership_v1_membership_proto_rawDesc), len(file_membership_v1_membership_proto_rawDesc)))
	})
	return file_membership_v1_membership_proto_rawDescData
}

var file_membership_v1_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_membership_v1_membership_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: api.membership.v1.RegisterRequest
	(*RegisterReply)(nil),         // 1: api.membership.v1.RegisterReply
	(*LoginRequest)(nil),          // 2: api.membership.v1.LoginRequest
	(*LoginReply)(nil),            // 3: api.membership.v1.LoginReply
	(*RefreshTokenRequest)(nil),   // 4: api.membership.v1.RefreshTokenRequest
	(*RefreshTokenReply)(nil),     // 5: api.membership.v1.RefreshTokenReply
	(*GetProfileRequest)(nil),     // 6: api.membership.v1.GetProfileRequest
	(*GetProfileReply)(nil),       // 7: api.membership.v1.GetProfileReply
	(*UpdateProfileRequest)(nil),  // 8: api.membership.v1.UpdateProfileRequest
	(*UpdateProfileReply)(nil),    // 9: api.membership.v1.UpdateProfileReply
	(*User)(nil),                  // 10: api.membership.v1.User
	(*GetAssetsRequest)(nil),      // 11: api.membership.v1.GetAssetsRequest
	(*GetAssetsReply)(nil),        // 12: api.membership.v1.GetAssetsReply
	(*UpdateAssetRequest)(nil),    // 13: api.membership.v1.UpdateAssetRequest
	(*UpdateAssetReply)(nil),      // 14: api.membership.v1.UpdateAssetReply
	(*Asset)(nil),                 // 15: api.membership.v1.Asset
	(*GetReferralsRequest)(nil),   // 16: api.membership.v1.GetReferralsRequest
	(*GetReferralsReply)(nil),     // 17: api.membership.v1.GetReferralsReply
	(*Referral)(nil),              // 18: api.membership.v1.Referral
	(*WithdrawalRequest)(nil),     // 19: api.membership.v1.WithdrawalRequest
	(*WithdrawalReply)(nil),       // 20: api.membership.v1.WithdrawalReply
	(*GetWithdrawalsRequest)(nil), // 21: api.membership.v1.GetWithdrawalsRequest
	(*GetWithdrawalsReply)(nil),   // 22: api.membership.v1.GetWithdrawalsReply
	(*Withdrawal)(nil),            // 23: api.membership.v1.Withdrawal
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
}
var file_membership_v1_membership_proto_depIdxs = []int32{
	24, // 0: api.membership.v1.RegisterReply.expires_at:type_name -> google.protobuf.Timestamp
	24, // 1: api.membership.v1.LoginReply.expires_at:type_name -> google.protobuf.Timestamp
	24, // 2: api.membership.v1.RefreshTokenReply.expires_at:type_name -> google.protobuf.Timestamp
	10, // 3: api.membership.v1.GetProfileReply.user:type_name -> api.membership.v1.User
	10, // 4: api.membership.v1.UpdateProfileReply.user:type_name -> api.membership.v1.User
	24, // 5: api.membership.v1.User.created_at:type_name -> google.protobuf.Timestamp
	24, // 6: api.membership.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	15, // 7: api.membership.v1.GetAssetsReply.assets:type_name -> api.membership.v1.Asset
	15, // 8: api.membership.v1.UpdateAssetReply.asset:type_name -> api.membership.v1.Asset
	24, // 9: api.membership.v1.Asset.created_at:type_name -> google.protobuf.Timestamp
	24, // 10: api.membership.v1.Asset.updated_at:type_name -> google.protobuf.Timestamp
	18, // 11: api.membership.v1.GetReferralsReply.referrals:type_name -> api.membership.v1.Referral
	24, // 12: api.membership.v1.Referral.created_at:type_name -> google.protobuf.Timestamp
	23, // 13: api.membership.v1.WithdrawalReply.withdrawal:type_name -> api.membership.v1.Withdrawal
	23, // 14: api.membership.v1.GetWithdrawalsReply.withdrawals:type_name -> api.membership.v1.Withdrawal
	24, // 15: api.membership.v1.Withdrawal.created_at:type_name -> google.protobuf.Timestamp
	24, // 16: api.membership.v1.Withdrawal.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 17: api.membership.v1.Membership.Register:input_type -> api.membership.v1.RegisterRequest
	2,  // 18: api.membership.v1.Membership.Login:input_type -> api.membership.v1.LoginRequest
	4,  // 19: api.membership.v1.Membership.RefreshToken:input_type -> api.membership.v1.RefreshTokenRequest
	6,  // 20: api.membership.v1.Membership.GetProfile:input_type -> api.membership.v1.GetProfileRequest
	8,  // 21: api.membership.v1.Membership.UpdateProfile:input_type -> api.membership.v1.UpdateProfileRequest
	11, // 22: api.membership.v1.Membership.GetAssets:input_type -> api.membership.v1.GetAssetsRequest
	13, // 23: api.membership.v1.Membership.UpdateAsset:input_type -> api.membership.v1.UpdateAssetRequest
	16, // 24: api.membership.v1.Membership.GetReferrals:input_type -> api.membership.v1.GetReferralsRequest
	19, // 25: api.membership.v1.Membership.RequestWithdrawal:input_type -> api.membership.v1.WithdrawalRequest
	21, // 26: api.membership.v1.Membership.GetWithdrawals:input_type -> api.membership.v1.GetWithdrawalsRequest
	1,  // 27: api.membership.v1.Membership.Register:output_type -> api.membership.v1.RegisterReply
	3,  // 28: api.membership.v1.Membership.Login:output_type -> api.membership.v1.LoginReply
	5,  // 29: api.membership.v1.Membership.RefreshToken:output_type -> api.membership.v1.RefreshTokenReply
	7,  // 30: api.membership.v1.Membership.GetProfile:output_type -> api.membership.v1.GetProfileReply
	9,  // 31: api.membership.v1.Membership.UpdateProfile:output_type -> api.membership.v1.UpdateProfileReply
	12, // 32: api.membership.v1.Membership.GetAssets:output_type -> api.membership.v1.GetAssetsReply
	14, // 33: api.membership.v1.Membership.UpdateAsset:output_type -> api.membership.v1.UpdateAssetReply
	17, // 34: api.membership.v1.Membership.GetReferrals:output_type -> api.membership.v1.GetReferralsReply
	20, // 35: api.membership.v1.Membership.RequestWithdrawal:output_type -> api.membership.v1.WithdrawalReply
	22, // 36: api.membership.v1.Membership.GetWithdrawals:output_type -> api.membership.v1.GetWithdrawalsReply
	27, // [27:37] is the sub-list for method output_type
	17, // [17:27] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_membership_v1_membership_proto_init() }
func file_membership_v1_membership_proto_init() {
	if File_membership_v1_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_membership_v1_membership_proto_rawDesc), len(file_membership_v1_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_membership_v1_membership_proto_goTypes,
		DependencyIndexes: file_membership_v1_membership_proto_depIdxs,
		MessageInfos:      file_membership_v1_membership_proto_msgTypes,
	}.Build()
	File_membership_v1_membership_proto = out.File
	file_membership_v1_membership_proto_goTypes = nil
	file_membership_v1_membership_proto_depIdxs = nil
}
