// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.12
// source: banking/v1/banking.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBankingGetCardInfo = "/api.banking.v1.Banking/GetCardInfo"
const OperationBankingGetCreditCardBalance = "/api.banking.v1.Banking/GetCreditCardBalance"
const OperationBankingGetExchangeRate = "/api.banking.v1.Banking/GetExchangeRate"
const OperationBankingGetPhysicalCardDetails = "/api.banking.v1.Banking/GetPhysicalCardDetails"
const OperationBankingGetRemittanceStatus = "/api.banking.v1.Banking/GetRemittanceStatus"
const OperationBankingInitiateRemittance = "/api.banking.v1.Banking/InitiateRemittance"
const OperationBankingListCards = "/api.banking.v1.Banking/ListCards"
const OperationBankingListRemittances = "/api.banking.v1.Banking/ListRemittances"

type BankingHTTPServer interface {
	// GetCardInfo Card Information
	GetCardInfo(context.Context, *GetCardInfoRequest) (*GetCardInfoReply, error)
	// GetCreditCardBalance Credit Card Balance
	GetCreditCardBalance(context.Context, *GetCreditCardBalanceRequest) (*GetCreditCardBalanceReply, error)
	// GetExchangeRate Exchange Rates
	GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateReply, error)
	// GetPhysicalCardDetails Physical Card Display
	GetPhysicalCardDetails(context.Context, *GetPhysicalCardDetailsRequest) (*GetPhysicalCardDetailsReply, error)
	GetRemittanceStatus(context.Context, *GetRemittanceStatusRequest) (*GetRemittanceStatusReply, error)
	// InitiateRemittance Global Remittance
	InitiateRemittance(context.Context, *InitiateRemittanceRequest) (*InitiateRemittanceReply, error)
	ListCards(context.Context, *ListCardsRequest) (*ListCardsReply, error)
	ListRemittances(context.Context, *ListRemittancesRequest) (*ListRemittancesReply, error)
}

func RegisterBankingHTTPServer(s *http.Server, srv BankingHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/banking/cards/{card_id}", _Banking_GetCardInfo0_HTTP_Handler(srv))
	r.GET("/v1/banking/cards", _Banking_ListCards0_HTTP_Handler(srv))
	r.GET("/v1/banking/cards/{card_id}/balance", _Banking_GetCreditCardBalance0_HTTP_Handler(srv))
	r.GET("/v1/banking/cards/{card_id}/physical", _Banking_GetPhysicalCardDetails0_HTTP_Handler(srv))
	r.POST("/v1/banking/remittance", _Banking_InitiateRemittance0_HTTP_Handler(srv))
	r.GET("/v1/banking/remittance/{transaction_id}", _Banking_GetRemittanceStatus0_HTTP_Handler(srv))
	r.GET("/v1/banking/remittance", _Banking_ListRemittances0_HTTP_Handler(srv))
	r.GET("/v1/banking/exchange-rate", _Banking_GetExchangeRate0_HTTP_Handler(srv))
}

func _Banking_GetCardInfo0_HTTP_Handler(srv BankingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCardInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBankingGetCardInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCardInfo(ctx, req.(*GetCardInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCardInfoReply)
		return ctx.Result(200, reply)
	}
}

func _Banking_ListCards0_HTTP_Handler(srv BankingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCardsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBankingListCards)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCards(ctx, req.(*ListCardsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCardsReply)
		return ctx.Result(200, reply)
	}
}

func _Banking_GetCreditCardBalance0_HTTP_Handler(srv BankingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCreditCardBalanceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBankingGetCreditCardBalance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCreditCardBalance(ctx, req.(*GetCreditCardBalanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCreditCardBalanceReply)
		return ctx.Result(200, reply)
	}
}

func _Banking_GetPhysicalCardDetails0_HTTP_Handler(srv BankingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPhysicalCardDetailsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBankingGetPhysicalCardDetails)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPhysicalCardDetails(ctx, req.(*GetPhysicalCardDetailsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPhysicalCardDetailsReply)
		return ctx.Result(200, reply)
	}
}

func _Banking_InitiateRemittance0_HTTP_Handler(srv BankingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InitiateRemittanceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBankingInitiateRemittance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InitiateRemittance(ctx, req.(*InitiateRemittanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InitiateRemittanceReply)
		return ctx.Result(200, reply)
	}
}

func _Banking_GetRemittanceStatus0_HTTP_Handler(srv BankingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRemittanceStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBankingGetRemittanceStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRemittanceStatus(ctx, req.(*GetRemittanceStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRemittanceStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Banking_ListRemittances0_HTTP_Handler(srv BankingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRemittancesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBankingListRemittances)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRemittances(ctx, req.(*ListRemittancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRemittancesReply)
		return ctx.Result(200, reply)
	}
}

func _Banking_GetExchangeRate0_HTTP_Handler(srv BankingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExchangeRateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBankingGetExchangeRate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExchangeRate(ctx, req.(*GetExchangeRateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExchangeRateReply)
		return ctx.Result(200, reply)
	}
}

type BankingHTTPClient interface {
	// GetCardInfo Card Information
	GetCardInfo(ctx context.Context, req *GetCardInfoRequest, opts ...http.CallOption) (rsp *GetCardInfoReply, err error)
	// GetCreditCardBalance Credit Card Balance
	GetCreditCardBalance(ctx context.Context, req *GetCreditCardBalanceRequest, opts ...http.CallOption) (rsp *GetCreditCardBalanceReply, err error)
	// GetExchangeRate Exchange Rates
	GetExchangeRate(ctx context.Context, req *GetExchangeRateRequest, opts ...http.CallOption) (rsp *GetExchangeRateReply, err error)
	// GetPhysicalCardDetails Physical Card Display
	GetPhysicalCardDetails(ctx context.Context, req *GetPhysicalCardDetailsRequest, opts ...http.CallOption) (rsp *GetPhysicalCardDetailsReply, err error)
	GetRemittanceStatus(ctx context.Context, req *GetRemittanceStatusRequest, opts ...http.CallOption) (rsp *GetRemittanceStatusReply, err error)
	// InitiateRemittance Global Remittance
	InitiateRemittance(ctx context.Context, req *InitiateRemittanceRequest, opts ...http.CallOption) (rsp *InitiateRemittanceReply, err error)
	ListCards(ctx context.Context, req *ListCardsRequest, opts ...http.CallOption) (rsp *ListCardsReply, err error)
	ListRemittances(ctx context.Context, req *ListRemittancesRequest, opts ...http.CallOption) (rsp *ListRemittancesReply, err error)
}

type BankingHTTPClientImpl struct {
	cc *http.Client
}

func NewBankingHTTPClient(client *http.Client) BankingHTTPClient {
	return &BankingHTTPClientImpl{client}
}

// GetCardInfo Card Information
func (c *BankingHTTPClientImpl) GetCardInfo(ctx context.Context, in *GetCardInfoRequest, opts ...http.CallOption) (*GetCardInfoReply, error) {
	var out GetCardInfoReply
	pattern := "/v1/banking/cards/{card_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBankingGetCardInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCreditCardBalance Credit Card Balance
func (c *BankingHTTPClientImpl) GetCreditCardBalance(ctx context.Context, in *GetCreditCardBalanceRequest, opts ...http.CallOption) (*GetCreditCardBalanceReply, error) {
	var out GetCreditCardBalanceReply
	pattern := "/v1/banking/cards/{card_id}/balance"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBankingGetCreditCardBalance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExchangeRate Exchange Rates
func (c *BankingHTTPClientImpl) GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...http.CallOption) (*GetExchangeRateReply, error) {
	var out GetExchangeRateReply
	pattern := "/v1/banking/exchange-rate"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBankingGetExchangeRate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPhysicalCardDetails Physical Card Display
func (c *BankingHTTPClientImpl) GetPhysicalCardDetails(ctx context.Context, in *GetPhysicalCardDetailsRequest, opts ...http.CallOption) (*GetPhysicalCardDetailsReply, error) {
	var out GetPhysicalCardDetailsReply
	pattern := "/v1/banking/cards/{card_id}/physical"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBankingGetPhysicalCardDetails))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BankingHTTPClientImpl) GetRemittanceStatus(ctx context.Context, in *GetRemittanceStatusRequest, opts ...http.CallOption) (*GetRemittanceStatusReply, error) {
	var out GetRemittanceStatusReply
	pattern := "/v1/banking/remittance/{transaction_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBankingGetRemittanceStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// InitiateRemittance Global Remittance
func (c *BankingHTTPClientImpl) InitiateRemittance(ctx context.Context, in *InitiateRemittanceRequest, opts ...http.CallOption) (*InitiateRemittanceReply, error) {
	var out InitiateRemittanceReply
	pattern := "/v1/banking/remittance"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBankingInitiateRemittance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BankingHTTPClientImpl) ListCards(ctx context.Context, in *ListCardsRequest, opts ...http.CallOption) (*ListCardsReply, error) {
	var out ListCardsReply
	pattern := "/v1/banking/cards"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBankingListCards))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BankingHTTPClientImpl) ListRemittances(ctx context.Context, in *ListRemittancesRequest, opts ...http.CallOption) (*ListRemittancesReply, error) {
	var out ListRemittancesReply
	pattern := "/v1/banking/remittance"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBankingListRemittances))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
