// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: banking/v1/banking.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Card Information Messages
type GetCardInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardInfoRequest) Reset() {
	*x = GetCardInfoRequest{}
	mi := &file_banking_v1_banking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardInfoRequest) ProtoMessage() {}

func (x *GetCardInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCardInfoRequest) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{0}
}

func (x *GetCardInfoRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type GetCardInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardInfoReply) Reset() {
	*x = GetCardInfoReply{}
	mi := &file_banking_v1_banking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardInfoReply) ProtoMessage() {}

func (x *GetCardInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardInfoReply.ProtoReflect.Descriptor instead.
func (*GetCardInfoReply) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{1}
}

func (x *GetCardInfoReply) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type ListCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsRequest) Reset() {
	*x = ListCardsRequest{}
	mi := &file_banking_v1_banking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsRequest) ProtoMessage() {}

func (x *ListCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsRequest.ProtoReflect.Descriptor instead.
func (*ListCardsRequest) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{2}
}

func (x *ListCardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListCardsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCardsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsReply) Reset() {
	*x = ListCardsReply{}
	mi := &file_banking_v1_banking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsReply) ProtoMessage() {}

func (x *ListCardsReply) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsReply.ProtoReflect.Descriptor instead.
func (*ListCardsReply) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{3}
}

func (x *ListCardsReply) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *ListCardsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Card struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardNumberMasked string                 `protobuf:"bytes,3,opt,name=card_number_masked,json=cardNumberMasked,proto3" json:"card_number_masked,omitempty"` // e.g., "**** **** **** 1234"
	CardType         string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`                           // "credit" or "debit"
	CardBrand        string                 `protobuf:"bytes,5,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`                        // "visa", "mastercard", etc.
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                               // "active", "blocked", "expired"
	ExpiryDate       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_banking_v1_banking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{4}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Card) GetCardNumberMasked() string {
	if x != nil {
		return x.CardNumberMasked
	}
	return ""
}

func (x *Card) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Card) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *Card) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Card) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Credit Card Balance Messages
type GetCreditCardBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreditCardBalanceRequest) Reset() {
	*x = GetCreditCardBalanceRequest{}
	mi := &file_banking_v1_banking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditCardBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditCardBalanceRequest) ProtoMessage() {}

func (x *GetCreditCardBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditCardBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetCreditCardBalanceRequest) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{5}
}

func (x *GetCreditCardBalanceRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type GetCreditCardBalanceReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CardId             string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AvailableBalance   float64                `protobuf:"fixed64,2,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	CreditLimit        float64                `protobuf:"fixed64,3,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
	OutstandingBalance float64                `protobuf:"fixed64,4,opt,name=outstanding_balance,json=outstandingBalance,proto3" json:"outstanding_balance,omitempty"`
	Currency           string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	LastUpdated        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCreditCardBalanceReply) Reset() {
	*x = GetCreditCardBalanceReply{}
	mi := &file_banking_v1_banking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditCardBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditCardBalanceReply) ProtoMessage() {}

func (x *GetCreditCardBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditCardBalanceReply.ProtoReflect.Descriptor instead.
func (*GetCreditCardBalanceReply) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{6}
}

func (x *GetCreditCardBalanceReply) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *GetCreditCardBalanceReply) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *GetCreditCardBalanceReply) GetCreditLimit() float64 {
	if x != nil {
		return x.CreditLimit
	}
	return 0
}

func (x *GetCreditCardBalanceReply) GetOutstandingBalance() float64 {
	if x != nil {
		return x.OutstandingBalance
	}
	return 0
}

func (x *GetCreditCardBalanceReply) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetCreditCardBalanceReply) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// Physical Card Details Messages
type GetPhysicalCardDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhysicalCardDetailsRequest) Reset() {
	*x = GetPhysicalCardDetailsRequest{}
	mi := &file_banking_v1_banking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhysicalCardDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhysicalCardDetailsRequest) ProtoMessage() {}

func (x *GetPhysicalCardDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhysicalCardDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetPhysicalCardDetailsRequest) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{7}
}

func (x *GetPhysicalCardDetailsRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type GetPhysicalCardDetailsReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CardId           string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	CardNumberMasked string                 `protobuf:"bytes,2,opt,name=card_number_masked,json=cardNumberMasked,proto3" json:"card_number_masked,omitempty"`
	CardholderName   string                 `protobuf:"bytes,3,opt,name=cardholder_name,json=cardholderName,proto3" json:"cardholder_name,omitempty"`
	ExpiryDate       string                 `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"` // MM/YY format
	CvvMasked        string                 `protobuf:"bytes,5,opt,name=cvv_masked,json=cvvMasked,proto3" json:"cvv_masked,omitempty"`    // "***"
	CardType         string                 `protobuf:"bytes,6,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	CardBrand        string                 `protobuf:"bytes,7,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPhysicalCardDetailsReply) Reset() {
	*x = GetPhysicalCardDetailsReply{}
	mi := &file_banking_v1_banking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhysicalCardDetailsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhysicalCardDetailsReply) ProtoMessage() {}

func (x *GetPhysicalCardDetailsReply) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhysicalCardDetailsReply.ProtoReflect.Descriptor instead.
func (*GetPhysicalCardDetailsReply) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{8}
}

func (x *GetPhysicalCardDetailsReply) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *GetPhysicalCardDetailsReply) GetCardNumberMasked() string {
	if x != nil {
		return x.CardNumberMasked
	}
	return ""
}

func (x *GetPhysicalCardDetailsReply) GetCardholderName() string {
	if x != nil {
		return x.CardholderName
	}
	return ""
}

func (x *GetPhysicalCardDetailsReply) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *GetPhysicalCardDetailsReply) GetCvvMasked() string {
	if x != nil {
		return x.CvvMasked
	}
	return ""
}

func (x *GetPhysicalCardDetailsReply) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *GetPhysicalCardDetailsReply) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

// Global Remittance Messages
type InitiateRemittanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromAccount     string                 `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount       string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount          float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	FromCurrency    string                 `protobuf:"bytes,4,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"` // ISO 4217
	ToCurrency      string                 `protobuf:"bytes,5,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`       // ISO 4217
	BeneficiaryName string                 `protobuf:"bytes,6,opt,name=beneficiary_name,json=beneficiaryName,proto3" json:"beneficiary_name,omitempty"`
	BeneficiaryBank string                 `protobuf:"bytes,7,opt,name=beneficiary_bank,json=beneficiaryBank,proto3" json:"beneficiary_bank,omitempty"`
	Purpose         string                 `protobuf:"bytes,8,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiateRemittanceRequest) Reset() {
	*x = InitiateRemittanceRequest{}
	mi := &file_banking_v1_banking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateRemittanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateRemittanceRequest) ProtoMessage() {}

func (x *InitiateRemittanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateRemittanceRequest.ProtoReflect.Descriptor instead.
func (*InitiateRemittanceRequest) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{9}
}

func (x *InitiateRemittanceRequest) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *InitiateRemittanceRequest) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *InitiateRemittanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiateRemittanceRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *InitiateRemittanceRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *InitiateRemittanceRequest) GetBeneficiaryName() string {
	if x != nil {
		return x.BeneficiaryName
	}
	return ""
}

func (x *InitiateRemittanceRequest) GetBeneficiaryBank() string {
	if x != nil {
		return x.BeneficiaryBank
	}
	return ""
}

func (x *InitiateRemittanceRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type InitiateRemittanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "processing", "completed", "failed"
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ExchangeRate  float64                `protobuf:"fixed64,4,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	Fee           float64                `protobuf:"fixed64,5,opt,name=fee,proto3" json:"fee,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateRemittanceReply) Reset() {
	*x = InitiateRemittanceReply{}
	mi := &file_banking_v1_banking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateRemittanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateRemittanceReply) ProtoMessage() {}

func (x *InitiateRemittanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateRemittanceReply.ProtoReflect.Descriptor instead.
func (*InitiateRemittanceReply) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{10}
}

func (x *InitiateRemittanceReply) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *InitiateRemittanceReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InitiateRemittanceReply) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiateRemittanceReply) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *InitiateRemittanceReply) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *InitiateRemittanceReply) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *InitiateRemittanceReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetRemittanceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemittanceStatusRequest) Reset() {
	*x = GetRemittanceStatusRequest{}
	mi := &file_banking_v1_banking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemittanceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemittanceStatusRequest) ProtoMessage() {}

func (x *GetRemittanceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemittanceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRemittanceStatusRequest) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{11}
}

func (x *GetRemittanceStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetRemittanceStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remittance    *Remittance            `protobuf:"bytes,1,opt,name=remittance,proto3" json:"remittance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRemittanceStatusReply) Reset() {
	*x = GetRemittanceStatusReply{}
	mi := &file_banking_v1_banking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRemittanceStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRemittanceStatusReply) ProtoMessage() {}

func (x *GetRemittanceStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRemittanceStatusReply.ProtoReflect.Descriptor instead.
func (*GetRemittanceStatusReply) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{12}
}

func (x *GetRemittanceStatusReply) GetRemittance() *Remittance {
	if x != nil {
		return x.Remittance
	}
	return nil
}

type ListRemittancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemittancesRequest) Reset() {
	*x = ListRemittancesRequest{}
	mi := &file_banking_v1_banking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemittancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemittancesRequest) ProtoMessage() {}

func (x *ListRemittancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemittancesRequest.ProtoReflect.Descriptor instead.
func (*ListRemittancesRequest) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{13}
}

func (x *ListRemittancesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListRemittancesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRemittancesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRemittancesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListRemittancesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remittances   []*Remittance          `protobuf:"bytes,1,rep,name=remittances,proto3" json:"remittances,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemittancesReply) Reset() {
	*x = ListRemittancesReply{}
	mi := &file_banking_v1_banking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemittancesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemittancesReply) ProtoMessage() {}

func (x *ListRemittancesReply) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemittancesReply.ProtoReflect.Descriptor instead.
func (*ListRemittancesReply) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{14}
}

func (x *ListRemittancesReply) GetRemittances() []*Remittance {
	if x != nil {
		return x.Remittances
	}
	return nil
}

func (x *ListRemittancesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Remittance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FromAccount     string                 `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount       string                 `protobuf:"bytes,3,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	FromCurrency    string                 `protobuf:"bytes,5,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency      string                 `protobuf:"bytes,6,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	ExchangeRate    float64                `protobuf:"fixed64,7,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	Fee             float64                `protobuf:"fixed64,8,opt,name=fee,proto3" json:"fee,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	BeneficiaryName string                 `protobuf:"bytes,10,opt,name=beneficiary_name,json=beneficiaryName,proto3" json:"beneficiary_name,omitempty"`
	BeneficiaryBank string                 `protobuf:"bytes,11,opt,name=beneficiary_bank,json=beneficiaryBank,proto3" json:"beneficiary_bank,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Remittance) Reset() {
	*x = Remittance{}
	mi := &file_banking_v1_banking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Remittance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Remittance) ProtoMessage() {}

func (x *Remittance) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Remittance.ProtoReflect.Descriptor instead.
func (*Remittance) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{15}
}

func (x *Remittance) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Remittance) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *Remittance) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *Remittance) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Remittance) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *Remittance) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *Remittance) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *Remittance) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Remittance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Remittance) GetBeneficiaryName() string {
	if x != nil {
		return x.BeneficiaryName
	}
	return ""
}

func (x *Remittance) GetBeneficiaryBank() string {
	if x != nil {
		return x.BeneficiaryBank
	}
	return ""
}

func (x *Remittance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Remittance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Exchange Rate Messages
type GetExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateRequest) Reset() {
	*x = GetExchangeRateRequest{}
	mi := &file_banking_v1_banking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateRequest) ProtoMessage() {}

func (x *GetExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{16}
}

func (x *GetExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type GetExchangeRateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateReply) Reset() {
	*x = GetExchangeRateReply{}
	mi := &file_banking_v1_banking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateReply) ProtoMessage() {}

func (x *GetExchangeRateReply) ProtoReflect() protoreflect.Message {
	mi := &file_banking_v1_banking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateReply.ProtoReflect.Descriptor instead.
func (*GetExchangeRateReply) Descriptor() ([]byte, []int) {
	return file_banking_v1_banking_proto_rawDescGZIP(), []int{17}
}

func (x *GetExchangeRateReply) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetExchangeRateReply) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *GetExchangeRateReply) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *GetExchangeRateReply) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_banking_v1_banking_proto protoreflect.FileDescriptor

const file_banking_v1_banking_proto_rawDesc = "" +
	"\n" +
	"\x18banking/v1/banking.proto\x12\x0eapi.banking.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"6\n" +
	"\x12GetCardInfoRequest\x12 \n" +
	"\acard_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06cardId\"<\n" +
	"\x10GetCardInfoReply\x12(\n" +
	"\x04card\x18\x01 \x01(\v2\x14.api.banking.v1.CardR\x04card\"\\\n" +
	"\x10ListCardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"R\n" +
	"\x0eListCardsReply\x12*\n" +
	"\x05cards\x18\x01 \x03(\v2\x14.api.banking.v1.CardR\x05cards\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa9\x02\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12,\n" +
	"\x12card_number_masked\x18\x03 \x01(\tR\x10cardNumberMasked\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x05 \x01(\tR\tcardBrand\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12;\n" +
	"\vexpiry_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"?\n" +
	"\x1bGetCreditCardBalanceRequest\x12 \n" +
	"\acard_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06cardId\"\x90\x02\n" +
	"\x19GetCreditCardBalanceReply\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12+\n" +
	"\x11available_balance\x18\x02 \x01(\x01R\x10availableBalance\x12!\n" +
	"\fcredit_limit\x18\x03 \x01(\x01R\vcreditLimit\x12/\n" +
	"\x13outstanding_balance\x18\x04 \x01(\x01R\x12outstandingBalance\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12=\n" +
	"\flast_updated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"A\n" +
	"\x1dGetPhysicalCardDetailsRequest\x12 \n" +
	"\acard_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06cardId\"\x89\x02\n" +
	"\x1bGetPhysicalCardDetailsReply\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12,\n" +
	"\x12card_number_masked\x18\x02 \x01(\tR\x10cardNumberMasked\x12'\n" +
	"\x0fcardholder_name\x18\x03 \x01(\tR\x0ecardholderName\x12\x1f\n" +
	"\vexpiry_date\x18\x04 \x01(\tR\n" +
	"expiryDate\x12\x1d\n" +
	"\n" +
	"cvv_masked\x18\x05 \x01(\tR\tcvvMasked\x12\x1b\n" +
	"\tcard_type\x18\x06 \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"card_brand\x18\a \x01(\tR\tcardBrand\"\xe1\x02\n" +
	"\x19InitiateRemittanceRequest\x12*\n" +
	"\ffrom_account\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vfromAccount\x12&\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\ttoAccount\x12&\n" +
	"\x06amount\x18\x03 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\x12-\n" +
	"\rfrom_currency\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\ffromCurrency\x12)\n" +
	"\vto_currency\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\n" +
	"toCurrency\x12)\n" +
	"\x10beneficiary_name\x18\x06 \x01(\tR\x0fbeneficiaryName\x12)\n" +
	"\x10beneficiary_bank\x18\a \x01(\tR\x0fbeneficiaryBank\x12\x18\n" +
	"\apurpose\x18\b \x01(\tR\apurpose\"\x85\x02\n" +
	"\x17InitiateRemittanceReply\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12#\n" +
	"\rexchange_rate\x18\x04 \x01(\x01R\fexchangeRate\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x01R\x03fee\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x01R\vtotalAmount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"L\n" +
	"\x1aGetRemittanceStatusRequest\x12.\n" +
	"\x0etransaction_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\rtransactionId\"V\n" +
	"\x18GetRemittanceStatusReply\x12:\n" +
	"\n" +
	"remittance\x18\x01 \x01(\v2\x1a.api.banking.v1.RemittanceR\n" +
	"remittance\"z\n" +
	"\x16ListRemittancesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"j\n" +
	"\x14ListRemittancesReply\x12<\n" +
	"\vremittances\x18\x01 \x03(\v2\x1a.api.banking.v1.RemittanceR\vremittances\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xee\x03\n" +
	"\n" +
	"Remittance\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12!\n" +
	"\ffrom_account\x18\x02 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x03 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12#\n" +
	"\rfrom_currency\x18\x05 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x06 \x01(\tR\n" +
	"toCurrency\x12#\n" +
	"\rexchange_rate\x18\a \x01(\x01R\fexchangeRate\x12\x10\n" +
	"\x03fee\x18\b \x01(\x01R\x03fee\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12)\n" +
	"\x10beneficiary_name\x18\n" +
	" \x01(\tR\x0fbeneficiaryName\x12)\n" +
	"\x10beneficiary_bank\x18\v \x01(\tR\x0fbeneficiaryBank\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\x16GetExchangeRateRequest\x12-\n" +
	"\rfrom_currency\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\ffromCurrency\x12)\n" +
	"\vto_currency\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\n" +
	"toCurrency\"\xaa\x01\n" +
	"\x14GetExchangeRateReply\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xe3\b\n" +
	"\aBanking\x12x\n" +
	"\vGetCardInfo\x12\".api.banking.v1.GetCardInfoRequest\x1a .api.banking.v1.GetCardInfoReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/banking/cards/{card_id}\x12h\n" +
	"\tListCards\x12 .api.banking.v1.ListCardsRequest\x1a\x1e.api.banking.v1.ListCardsReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/banking/cards\x12\x9b\x01\n" +
	"\x14GetCreditCardBalance\x12+.api.banking.v1.GetCreditCardBalanceRequest\x1a).api.banking.v1.GetCreditCardBalanceReply\"+\x82\xd3\xe4\x93\x02%\x12#/v1/banking/cards/{card_id}/balance\x12\xa2\x01\n" +
	"\x16GetPhysicalCardDetails\x12-.api.banking.v1.GetPhysicalCardDetailsRequest\x1a+.api.banking.v1.GetPhysicalCardDetailsReply\",\x82\xd3\xe4\x93\x02&\x12$/v1/banking/cards/{card_id}/physical\x12\x8b\x01\n" +
	"\x12InitiateRemittance\x12).api.banking.v1.InitiateRemittanceRequest\x1a'.api.banking.v1.InitiateRemittanceReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/banking/remittance\x12\x9c\x01\n" +
	"\x13GetRemittanceStatus\x12*.api.banking.v1.GetRemittanceStatusRequest\x1a(.api.banking.v1.GetRemittanceStatusReply\"/\x82\xd3\xe4\x93\x02)\x12'/v1/banking/remittance/{transaction_id}\x12\x7f\n" +
	"\x0fListRemittances\x12&.api.banking.v1.ListRemittancesRequest\x1a$.api.banking.v1.ListRemittancesReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/banking/remittance\x12\x82\x01\n" +
	"\x0fGetExchangeRate\x12&.api.banking.v1.GetExchangeRateRequest\x1a$.api.banking.v1.GetExchangeRateReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/banking/exchange-rateB#Z!banking-service/api/banking/v1;v1b\x06proto3"

var (
	file_banking_v1_banking_proto_rawDescOnce sync.Once
	file_banking_v1_banking_proto_rawDescData []byte
)

func file_banking_v1_banking_proto_rawDescGZIP() []byte {
	file_banking_v1_banking_proto_rawDescOnce.Do(func() {
		file_banking_v1_banking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_banking_v1_banking_proto_rawDesc), len(file_banking_v1_banking_proto_rawDesc)))
	})
	return file_banking_v1_banking_proto_rawDescData
}

var file_banking_v1_banking_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_banking_v1_banking_proto_goTypes = []any{
	(*GetCardInfoRequest)(nil),            // 0: api.banking.v1.GetCardInfoRequest
	(*GetCardInfoReply)(nil),              // 1: api.banking.v1.GetCardInfoReply
	(*ListCardsRequest)(nil),              // 2: api.banking.v1.ListCardsRequest
	(*ListCardsReply)(nil),                // 3: api.banking.v1.ListCardsReply
	(*Card)(nil),                          // 4: api.banking.v1.Card
	(*GetCreditCardBalanceRequest)(nil),   // 5: api.banking.v1.GetCreditCardBalanceRequest
	(*GetCreditCardBalanceReply)(nil),     // 6: api.banking.v1.GetCreditCardBalanceReply
	(*GetPhysicalCardDetailsRequest)(nil), // 7: api.banking.v1.GetPhysicalCardDetailsRequest
	(*GetPhysicalCardDetailsReply)(nil),   // 8: api.banking.v1.GetPhysicalCardDetailsReply
	(*InitiateRemittanceRequest)(nil),     // 9: api.banking.v1.InitiateRemittanceRequest
	(*InitiateRemittanceReply)(nil),       // 10: api.banking.v1.InitiateRemittanceReply
	(*GetRemittanceStatusRequest)(nil),    // 11: api.banking.v1.GetRemittanceStatusRequest
	(*GetRemittanceStatusReply)(nil),      // 12: api.banking.v1.GetRemittanceStatusReply
	(*ListRemittancesRequest)(nil),        // 13: api.banking.v1.ListRemittancesRequest
	(*ListRemittancesReply)(nil),          // 14: api.banking.v1.ListRemittancesReply
	(*Remittance)(nil),                    // 15: api.banking.v1.Remittance
	(*GetExchangeRateRequest)(nil),        // 16: api.banking.v1.GetExchangeRateRequest
	(*GetExchangeRateReply)(nil),          // 17: api.banking.v1.GetExchangeRateReply
	(*timestamppb.Timestamp)(nil),         // 18: google.protobuf.Timestamp
}
var file_banking_v1_banking_proto_depIdxs = []int32{
	4,  // 0: api.banking.v1.GetCardInfoReply.card:type_name -> api.banking.v1.Card
	4,  // 1: api.banking.v1.ListCardsReply.cards:type_name -> api.banking.v1.Card
	18, // 2: api.banking.v1.Card.expiry_date:type_name -> google.protobuf.Timestamp
	18, // 3: api.banking.v1.Card.created_at:type_name -> google.protobuf.Timestamp
	18, // 4: api.banking.v1.GetCreditCardBalanceReply.last_updated:type_name -> google.protobuf.Timestamp
	18, // 5: api.banking.v1.InitiateRemittanceReply.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: api.banking.v1.GetRemittanceStatusReply.remittance:type_name -> api.banking.v1.Remittance
	15, // 7: api.banking.v1.ListRemittancesReply.remittances:type_name -> api.banking.v1.Remittance
	18, // 8: api.banking.v1.Remittance.created_at:type_name -> google.protobuf.Timestamp
	18, // 9: api.banking.v1.Remittance.updated_at:type_name -> google.protobuf.Timestamp
	18, // 10: api.banking.v1.GetExchangeRateReply.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 11: api.banking.v1.Banking.GetCardInfo:input_type -> api.banking.v1.GetCardInfoRequest
	2,  // 12: api.banking.v1.Banking.ListCards:input_type -> api.banking.v1.ListCardsRequest
	5,  // 13: api.banking.v1.Banking.GetCreditCardBalance:input_type -> api.banking.v1.GetCreditCardBalanceRequest
	7,  // 14: api.banking.v1.Banking.GetPhysicalCardDetails:input_type -> api.banking.v1.GetPhysicalCardDetailsRequest
	9,  // 15: api.banking.v1.Banking.InitiateRemittance:input_type -> api.banking.v1.InitiateRemittanceRequest
	11, // 16: api.banking.v1.Banking.GetRemittanceStatus:input_type -> api.banking.v1.GetRemittanceStatusRequest
	13, // 17: api.banking.v1.Banking.ListRemittances:input_type -> api.banking.v1.ListRemittancesRequest
	16, // 18: api.banking.v1.Banking.GetExchangeRate:input_type -> api.banking.v1.GetExchangeRateRequest
	1,  // 19: api.banking.v1.Banking.GetCardInfo:output_type -> api.banking.v1.GetCardInfoReply
	3,  // 20: api.banking.v1.Banking.ListCards:output_type -> api.banking.v1.ListCardsReply
	6,  // 21: api.banking.v1.Banking.GetCreditCardBalance:output_type -> api.banking.v1.GetCreditCardBalanceReply
	8,  // 22: api.banking.v1.Banking.GetPhysicalCardDetails:output_type -> api.banking.v1.GetPhysicalCardDetailsReply
	10, // 23: api.banking.v1.Banking.InitiateRemittance:output_type -> api.banking.v1.InitiateRemittanceReply
	12, // 24: api.banking.v1.Banking.GetRemittanceStatus:output_type -> api.banking.v1.GetRemittanceStatusReply
	14, // 25: api.banking.v1.Banking.ListRemittances:output_type -> api.banking.v1.ListRemittancesReply
	17, // 26: api.banking.v1.Banking.GetExchangeRate:output_type -> api.banking.v1.GetExchangeRateReply
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_banking_v1_banking_proto_init() }
func file_banking_v1_banking_proto_init() {
	if File_banking_v1_banking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_banking_v1_banking_proto_rawDesc), len(file_banking_v1_banking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_banking_v1_banking_proto_goTypes,
		DependencyIndexes: file_banking_v1_banking_proto_depIdxs,
		MessageInfos:      file_banking_v1_banking_proto_msgTypes,
	}.Build()
	File_banking_v1_banking_proto = out.File
	file_banking_v1_banking_proto_goTypes = nil
	file_banking_v1_banking_proto_depIdxs = nil
}
