// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: banking/v1/banking.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Banking_GetCardInfo_FullMethodName            = "/api.banking.v1.Banking/GetCardInfo"
	Banking_ListCards_FullMethodName              = "/api.banking.v1.Banking/ListCards"
	Banking_GetCreditCardBalance_FullMethodName   = "/api.banking.v1.Banking/GetCreditCardBalance"
	Banking_GetPhysicalCardDetails_FullMethodName = "/api.banking.v1.Banking/GetPhysicalCardDetails"
	Banking_InitiateRemittance_FullMethodName     = "/api.banking.v1.Banking/InitiateRemittance"
	Banking_GetRemittanceStatus_FullMethodName    = "/api.banking.v1.Banking/GetRemittanceStatus"
	Banking_ListRemittances_FullMethodName        = "/api.banking.v1.Banking/ListRemittances"
	Banking_GetExchangeRate_FullMethodName        = "/api.banking.v1.Banking/GetExchangeRate"
)

// BankingClient is the client API for Banking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Banking service handles integration with upstream banking APIs
type BankingClient interface {
	// Card Information
	GetCardInfo(ctx context.Context, in *GetCardInfoRequest, opts ...grpc.CallOption) (*GetCardInfoReply, error)
	ListCards(ctx context.Context, in *ListCardsRequest, opts ...grpc.CallOption) (*ListCardsReply, error)
	// Credit Card Balance
	GetCreditCardBalance(ctx context.Context, in *GetCreditCardBalanceRequest, opts ...grpc.CallOption) (*GetCreditCardBalanceReply, error)
	// Physical Card Display
	GetPhysicalCardDetails(ctx context.Context, in *GetPhysicalCardDetailsRequest, opts ...grpc.CallOption) (*GetPhysicalCardDetailsReply, error)
	// Global Remittance
	InitiateRemittance(ctx context.Context, in *InitiateRemittanceRequest, opts ...grpc.CallOption) (*InitiateRemittanceReply, error)
	GetRemittanceStatus(ctx context.Context, in *GetRemittanceStatusRequest, opts ...grpc.CallOption) (*GetRemittanceStatusReply, error)
	ListRemittances(ctx context.Context, in *ListRemittancesRequest, opts ...grpc.CallOption) (*ListRemittancesReply, error)
	// Exchange Rates
	GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateReply, error)
}

type bankingClient struct {
	cc grpc.ClientConnInterface
}

func NewBankingClient(cc grpc.ClientConnInterface) BankingClient {
	return &bankingClient{cc}
}

func (c *bankingClient) GetCardInfo(ctx context.Context, in *GetCardInfoRequest, opts ...grpc.CallOption) (*GetCardInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardInfoReply)
	err := c.cc.Invoke(ctx, Banking_GetCardInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingClient) ListCards(ctx context.Context, in *ListCardsRequest, opts ...grpc.CallOption) (*ListCardsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCardsReply)
	err := c.cc.Invoke(ctx, Banking_ListCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingClient) GetCreditCardBalance(ctx context.Context, in *GetCreditCardBalanceRequest, opts ...grpc.CallOption) (*GetCreditCardBalanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCreditCardBalanceReply)
	err := c.cc.Invoke(ctx, Banking_GetCreditCardBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingClient) GetPhysicalCardDetails(ctx context.Context, in *GetPhysicalCardDetailsRequest, opts ...grpc.CallOption) (*GetPhysicalCardDetailsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhysicalCardDetailsReply)
	err := c.cc.Invoke(ctx, Banking_GetPhysicalCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingClient) InitiateRemittance(ctx context.Context, in *InitiateRemittanceRequest, opts ...grpc.CallOption) (*InitiateRemittanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateRemittanceReply)
	err := c.cc.Invoke(ctx, Banking_InitiateRemittance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingClient) GetRemittanceStatus(ctx context.Context, in *GetRemittanceStatusRequest, opts ...grpc.CallOption) (*GetRemittanceStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRemittanceStatusReply)
	err := c.cc.Invoke(ctx, Banking_GetRemittanceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingClient) ListRemittances(ctx context.Context, in *ListRemittancesRequest, opts ...grpc.CallOption) (*ListRemittancesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRemittancesReply)
	err := c.cc.Invoke(ctx, Banking_ListRemittances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankingClient) GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*GetExchangeRateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExchangeRateReply)
	err := c.cc.Invoke(ctx, Banking_GetExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankingServer is the server API for Banking service.
// All implementations must embed UnimplementedBankingServer
// for forward compatibility.
//
// Banking service handles integration with upstream banking APIs
type BankingServer interface {
	// Card Information
	GetCardInfo(context.Context, *GetCardInfoRequest) (*GetCardInfoReply, error)
	ListCards(context.Context, *ListCardsRequest) (*ListCardsReply, error)
	// Credit Card Balance
	GetCreditCardBalance(context.Context, *GetCreditCardBalanceRequest) (*GetCreditCardBalanceReply, error)
	// Physical Card Display
	GetPhysicalCardDetails(context.Context, *GetPhysicalCardDetailsRequest) (*GetPhysicalCardDetailsReply, error)
	// Global Remittance
	InitiateRemittance(context.Context, *InitiateRemittanceRequest) (*InitiateRemittanceReply, error)
	GetRemittanceStatus(context.Context, *GetRemittanceStatusRequest) (*GetRemittanceStatusReply, error)
	ListRemittances(context.Context, *ListRemittancesRequest) (*ListRemittancesReply, error)
	// Exchange Rates
	GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateReply, error)
	mustEmbedUnimplementedBankingServer()
}

// UnimplementedBankingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankingServer struct{}

func (UnimplementedBankingServer) GetCardInfo(context.Context, *GetCardInfoRequest) (*GetCardInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCardInfo not implemented")
}
func (UnimplementedBankingServer) ListCards(context.Context, *ListCardsRequest) (*ListCardsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCards not implemented")
}
func (UnimplementedBankingServer) GetCreditCardBalance(context.Context, *GetCreditCardBalanceRequest) (*GetCreditCardBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreditCardBalance not implemented")
}
func (UnimplementedBankingServer) GetPhysicalCardDetails(context.Context, *GetPhysicalCardDetailsRequest) (*GetPhysicalCardDetailsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPhysicalCardDetails not implemented")
}
func (UnimplementedBankingServer) InitiateRemittance(context.Context, *InitiateRemittanceRequest) (*InitiateRemittanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateRemittance not implemented")
}
func (UnimplementedBankingServer) GetRemittanceStatus(context.Context, *GetRemittanceStatusRequest) (*GetRemittanceStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRemittanceStatus not implemented")
}
func (UnimplementedBankingServer) ListRemittances(context.Context, *ListRemittancesRequest) (*ListRemittancesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRemittances not implemented")
}
func (UnimplementedBankingServer) GetExchangeRate(context.Context, *GetExchangeRateRequest) (*GetExchangeRateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeRate not implemented")
}
func (UnimplementedBankingServer) mustEmbedUnimplementedBankingServer() {}
func (UnimplementedBankingServer) testEmbeddedByValue()                 {}

// UnsafeBankingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankingServer will
// result in compilation errors.
type UnsafeBankingServer interface {
	mustEmbedUnimplementedBankingServer()
}

func RegisterBankingServer(s grpc.ServiceRegistrar, srv BankingServer) {
	// If the following call pancis, it indicates UnimplementedBankingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Banking_ServiceDesc, srv)
}

func _Banking_GetCardInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServer).GetCardInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banking_GetCardInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServer).GetCardInfo(ctx, req.(*GetCardInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banking_ListCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServer).ListCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banking_ListCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServer).ListCards(ctx, req.(*ListCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banking_GetCreditCardBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreditCardBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServer).GetCreditCardBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banking_GetCreditCardBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServer).GetCreditCardBalance(ctx, req.(*GetCreditCardBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banking_GetPhysicalCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhysicalCardDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServer).GetPhysicalCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banking_GetPhysicalCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServer).GetPhysicalCardDetails(ctx, req.(*GetPhysicalCardDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banking_InitiateRemittance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateRemittanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServer).InitiateRemittance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banking_InitiateRemittance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServer).InitiateRemittance(ctx, req.(*InitiateRemittanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banking_GetRemittanceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRemittanceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServer).GetRemittanceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banking_GetRemittanceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServer).GetRemittanceStatus(ctx, req.(*GetRemittanceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banking_ListRemittances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRemittancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServer).ListRemittances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banking_ListRemittances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServer).ListRemittances(ctx, req.(*ListRemittancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banking_GetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankingServer).GetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Banking_GetExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankingServer).GetExchangeRate(ctx, req.(*GetExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Banking_ServiceDesc is the grpc.ServiceDesc for Banking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Banking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.banking.v1.Banking",
	HandlerType: (*BankingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCardInfo",
			Handler:    _Banking_GetCardInfo_Handler,
		},
		{
			MethodName: "ListCards",
			Handler:    _Banking_ListCards_Handler,
		},
		{
			MethodName: "GetCreditCardBalance",
			Handler:    _Banking_GetCreditCardBalance_Handler,
		},
		{
			MethodName: "GetPhysicalCardDetails",
			Handler:    _Banking_GetPhysicalCardDetails_Handler,
		},
		{
			MethodName: "InitiateRemittance",
			Handler:    _Banking_InitiateRemittance_Handler,
		},
		{
			MethodName: "GetRemittanceStatus",
			Handler:    _Banking_GetRemittanceStatus_Handler,
		},
		{
			MethodName: "ListRemittances",
			Handler:    _Banking_ListRemittances_Handler,
		},
		{
			MethodName: "GetExchangeRate",
			Handler:    _Banking_GetExchangeRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "banking/v1/banking.proto",
}
