// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"membership-service/internal/biz"
	"membership-service/internal/conf"
	"membership-service/internal/data"
	"membership-service/internal/server"
	"membership-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	membershipRepo := data.NewMembershipRepo(dataData, logger)
	membershipUsecase := biz.NewMembershipUsecase(membershipRepo, logger)
	membershipService := service.NewMembershipService(membershipUsecase)
	grpcServer := server.NewGRPCServer(confServer, membershipService, logger)
	httpServer := server.NewHTTPServer(confServer, membershipService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
