// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"website-service/internal/biz"
	"website-service/internal/conf"
	"website-service/internal/data"
	"website-service/internal/server"
	"website-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	websiteRepo := data.NewWebsiteRepo(dataData, logger)
	websiteUsecase := biz.NewWebsiteUsecase(websiteRepo, logger)
	websiteService := service.NewWebsiteService(websiteUsecase)
	grpcServer := server.NewGRPCServer(confServer, websiteService, logger)
	httpServer := server.NewHTTPServer(confServer, websiteService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
